#define CATEGORY_CLIENT "CLIENT"
#define CATEGORY_ADMIN "ADMIN"
#define CATEGORY_CARBON "CARBON"
#define CATEGORY_HUMAN "HUMAN"
#define CATEGORY_MISC "MISC"
#define CATEGORY_ROBOT "ROBOT"

#define WEIGHT_HIGHEST 0
#define WEIGHT_CLIENT 10
#define WEIGHT_ADMIN 20
#define WEIGHT_MOB 30
#define WEIGHT_LIVING 40
#define WEIGHT_DEAD 50
#define WEIGHT_ROBOT 60
#define WEIGHT_LOWEST 999
