GLOBAL_LIST_INIT(bitfields, generate_bitfields())

/// Specifies a bitfield for smarter debugging
/datum/bitfield
	/// The variable name that contains the bitfield
	var/variable

	/// An associative list of the readable flag and its true value
	var/list/flags

/// Turns /datum/bitfield subtypes into a list for use in debugging
/proc/generate_bitfields()
	var/list/bitfields = list()
	for (var/_bitfield in subtypesof(/datum/bitfield))
		var/datum/bitfield/bitfield = new _bitfield
		bitfields[bitfield.variable] = bitfield.flags
	return bitfields

DEFINE_BITFIELD(admin_flags, list(
	"ADMIN" = R_ADMIN,
	"AUTOLOGIN" = R_AUTOADMIN,
	"BAN" = R_BAN,
	"BUILDMODE" = R_BUILD,
	"DBRANKS" = R_DBRANKS,
	"DEBUG" = R_DEBUG,
	"FUN" = R_FUN,
	"PERMISSIONS" = R_PERMISSIONS,
	"POLL" = R_POLL,
	"POSSESS" = R_POSSESS,
	"SERVER" = R_SERVER,
	"SOUNDS" = R_SOUND,
	"SPAWN" = R_SPAWN,
	"STEALTH" = R_STEALTH,
	"SUPPRESS" = R_SUPPRESS,
	"VAREDIT" = R_VAREDIT
))

DEFINE_BITFIELD(appearance_flags, list(
	"KEEP_APART" = KEEP_APART,
	"KEEP_TOGETHER" = KEEP_TOGETHER,
	"LONG_GLIDE" = LONG_GLIDE,
	"NO_CLIENT_COLOR" = NO_CLIENT_COLOR,
	"PASS_MOUSE" = PASS_MOUSE,
	"PIXEL_SCALE" = PIXEL_SCALE,
	"PLANE_MASTER" = PLANE_MASTER,
	"RESET_ALPHA" = RESET_ALPHA,
	"RESET_COLOR" = RESET_COLOR,
	"RESET_TRANSFORM" = RESET_TRANSFORM,
	"TILE_BOUND" = TILE_BOUND,
	"TILE_MOVER" = TILE_MOVER,
))

DEFINE_BITFIELD(area_flags, list(
	"BLOBS_ALLOWED" = BLOBS_ALLOWED,
	"BLOCK_SUICIDE" = BLOCK_SUICIDE,
	"CAVES_ALLOWED" = CAVES_ALLOWED,
	"FLORA_ALLOWED" = FLORA_ALLOWED,
	"HIDDEN_AREA" = HIDDEN_AREA,
	"HIDDEN_STASH_LOCATION" = HIDDEN_STASH_LOCATION,
	"MEGAFAUNA_SPAWN_ALLOWED" = MEGAFAUNA_SPAWN_ALLOWED,
	"MOB_SPAWN_ALLOWED" = MOB_SPAWN_ALLOWED,
	"UNIQUE_AREA" = UNIQUE_AREA,
	"VALID_TERRITORY" = VALID_TERRITORY,
	"XENOBIOLOGY_COMPATIBLE" = XENOBIOLOGY_COMPATIBLE,
))

DEFINE_BITFIELD(car_traits, list(
	"CAN_KIDNAP" = CAN_KIDNAP,
))

DEFINE_BITFIELD(clothing_flags, list(
	"BLOCK_GAS_SMOKE_EFFECT" = BLOCK_GAS_SMOKE_EFFECT,
	"EFFECT_HAT" = EFFECT_HAT,
	"HEADINTERNALS" = HEADINTERNALS,
	"LAVAPROTECT" = LAVAPROTECT,
	"MASKINTERNALS" = MASKINTERNALS,
	"NOSLIP" = NOSLIP,
	"SCAN_BOOZEPOWER" = SCAN_BOOZEPOWER,
	"SCAN_REAGENTS" = SCAN_REAGENTS,
	"SNUG_FIT" = SNUG_FIT,
	"STOPSPRESSUREDAMAGE" = STOPSPRESSUREDAMAGE,
	"THICKMATERIAL" = THICKMATERIAL,
	"VOICEBOX_DISABLED" = VOICEBOX_DISABLED,
	"VOICEBOX_TOGGLABLE" = VOICEBOX_TOGGLABLE,
))

DEFINE_BITFIELD(datum_flags, list(
	"DF_ISPROCESSING" = DF_ISPROCESSING,
	"DF_USE_TAG" = DF_USE_TAG,
	"DF_VAR_EDITED" = DF_VAR_EDITED,
))

DEFINE_BITFIELD(disease_flags, list(
	"CAN_CARRY"	= CAN_CARRY,
	"CAN_RESIST" = CAN_RESIST,
	"CURABLE" = CURABLE,
))

DEFINE_BITFIELD(flags_1, list(
	"ADMIN_SPAWNED_1" = ADMIN_SPAWNED_1,
	"CAN_BE_DIRTY_1" = CAN_BE_DIRTY_1,
	"CONDUCT_1" = CONDUCT_1,
	"HOLOGRAM_1" = HOLOGRAM_1,
	"INITIALIZED_1" = INITIALIZED_1,
	"IS_ONTOP_1" = IS_ONTOP_1,
	"NODECONSTRUCT_1" = NODECONSTRUCT_1,
	"NOJAUNT_1" = NOJAUNT_1,
	"NO_LAVA_GEN_1" = NO_LAVA_GEN_1,
	"NO_RUINS_1" = NO_RUINS_1,
	"ON_BORDER_1" = ON_BORDER_1,
	"OVERLAY_QUEUED_1" = OVERLAY_QUEUED_1,
	"PREVENT_CLICK_UNDER_1" = PREVENT_CLICK_UNDER_1,
	"PREVENT_CONTENTS_EXPLOSION_1" = PREVENT_CONTENTS_EXPLOSION_1,
	"TESLA_IGNORE_1" = TESLA_IGNORE_1,
	"UNPAINTABLE_1" = UNPAINTABLE_1,
	"UNUSED_RESERVATION_TURF_1" = UNUSED_RESERVATION_TURF_1,
))

DEFINE_BITFIELD(flags_inv, list(
	"HIDEEARS" = HIDEEARS,
	"HIDEEYES" = HIDEEYES,
	"HIDEFACE" = HIDEFACE,
	"HIDEFACIALHAIR" = HIDEFACIALHAIR,
	"HIDEGLOVES" = HIDEGLOVES,
	"HIDEHAIR" = HIDEHAIR,
	"HIDEJUMPSUIT" = HIDEJUMPSUIT,
	"HIDEMASK" = HIDEMASK,
	"HIDENECK" = HIDENECK,
	"HIDESHOES" = HIDESHOES,
	"HIDESNOUT" = HIDESNOUT,
	"HIDESUITSTORAGE" = HIDESUITSTORAGE,
))

DEFINE_BITFIELD(flags_ricochet, list(
	"RICOCHET_HARD" = RICOCHET_HARD,
	"RICOCHET_SHINY" = RICOCHET_SHINY,
))

DEFINE_BITFIELD(interaction_flags_atom, list(
	"INTERACT_ATOM_ALLOW_USER_LOCATION" = INTERACT_ATOM_ALLOW_USER_LOCATION,
	"INTERACT_ATOM_ATTACK_HAND" = INTERACT_ATOM_ATTACK_HAND,
	"INTERACT_ATOM_CHECK_GRAB" = INTERACT_ATOM_CHECK_GRAB,
	"INTERACT_ATOM_IGNORE_INCAPACITATED" = INTERACT_ATOM_IGNORE_INCAPACITATED,
	"INTERACT_ATOM_IGNORE_RESTRAINED" = INTERACT_ATOM_IGNORE_RESTRAINED,
	"INTERACT_ATOM_NO_FINGERPRINT_ATTACK_HAND" = INTERACT_ATOM_NO_FINGERPRINT_ATTACK_HAND,
	"INTERACT_ATOM_NO_FINGERPRINT_INTERACT" = INTERACT_ATOM_NO_FINGERPRINT_INTERACT,
	"INTERACT_ATOM_REQUIRES_ANCHORED" = INTERACT_ATOM_REQUIRES_ANCHORED,
	"INTERACT_ATOM_REQUIRES_DEXTERITY" = INTERACT_ATOM_REQUIRES_DEXTERITY,
	"INTERACT_ATOM_UI_INTERACT" = INTERACT_ATOM_UI_INTERACT,
))

DEFINE_BITFIELD(interaction_flags_machine, list(
	"INTERACT_MACHINE_ALLOW_SILICON" = INTERACT_MACHINE_ALLOW_SILICON,
	"INTERACT_MACHINE_OFFLINE" = INTERACT_MACHINE_OFFLINE,
	"INTERACT_MACHINE_OPEN" = INTERACT_MACHINE_OPEN,
	"INTERACT_MACHINE_OPEN_SILICON" = INTERACT_MACHINE_OPEN_SILICON,
	"INTERACT_MACHINE_REQUIRES_SILICON" = INTERACT_MACHINE_REQUIRES_SILICON,
	"INTERACT_MACHINE_SET_MACHINE" = INTERACT_MACHINE_SET_MACHINE,
	"INTERACT_MACHINE_WIRES_IF_OPEN" = INTERACT_MACHINE_WIRES_IF_OPEN
))

DEFINE_BITFIELD(interaction_flags_item, list(
	"INTERACT_ITEM_ATTACK_HAND_PICKUP" = INTERACT_ITEM_ATTACK_HAND_PICKUP,
))

DEFINE_BITFIELD(item_flags, list(
	"ABSTRACT" = ABSTRACT,
	"BEING_REMOVED" = BEING_REMOVED,
	"DROPDEL" = DROPDEL,
	"FORCE_STRING_OVERRIDE" = FORCE_STRING_OVERRIDE,
	"ILLEGAL" = ILLEGAL,
	"IN_STORAGE" = IN_STORAGE,
	"ISWEAPON" = ISWEAPON,
	"NEEDS_PERMIT" = NEEDS_PERMIT,
	"NO_MAT_REDEMPTION" = NO_MAT_REDEMPTION,
	"NO_PIXEL_RANDOM_DROP" = NO_PIXEL_RANDOM_DROP,
	"NOBLUDGEON" = NOBLUDGEON,
	"PICKED_UP" = PICKED_UP,
	"SLOWS_WHILE_IN_HAND" = SLOWS_WHILE_IN_HAND,
	"WAS_THROWN" = WAS_THROWN,
))

DEFINE_BITFIELD(sight, list(
	"BLIND" = BLIND,
	"SEE_BLACKNESS" = SEE_BLACKNESS,
	"SEE_INFRA" = SEE_INFRA,
	"SEE_MOBS" = SEE_MOBS,
	"SEE_OBJS" = SEE_OBJS,
	"SEE_PIXELS" = SEE_PIXELS,
	"SEE_SELF" = SEE_SELF,
	"SEE_THRU" = SEE_THRU,
	"SEE_TURFS" = SEE_TURFS
))

DEFINE_BITFIELD(obj_flags, list(
	"BEING_SHOCKED" = BEING_SHOCKED,
	"CAN_BE_HIT" = CAN_BE_HIT,
	"DANGEROUS_POSSESSION" = DANGEROUS_POSSESSION,
	"EMAGGED" = EMAGGED,
	"IN_USE" = IN_USE,
	"OBJ_EMPED" = OBJ_EMPED,
	"OBJ_SCANNED" = SCANNED,
	"ON_BLUEPRINTS" = ON_BLUEPRINTS,
	"UNIQUE_RENAME" = UNIQUE_RENAME,
	"USES_TGUI" = USES_TGUI,
))

DEFINE_BITFIELD(liked_foodtypes, list(
	"ALCOHOL" = ALCOHOL,
	"BREAKFAST" = BREAKFAST,
	"CLOTH" = CLOTH,
	"DAIRY" = DAIRY,
	"FRIED" = FRIED,
	"FRUIT" = FRUIT,
	"GORE" = GORE,
	"GRAIN" = GRAIN,
	"GROSS" = GROSS,
	"JUNKFOOD" = JUNKFOOD,
	"MEAT" = MEAT,
	"PINEAPPLE" = PINEAPPLE,
	"RAW" = RAW,
	"SUGAR" = SUGAR,
	"TOXIC" = TOXIC,
	"VEGETABLES" = VEGETABLES,
))

DEFINE_BITFIELD(disliked_foodtypes, list(
	"ALCOHOL" = ALCOHOL,
	"BREAKFAST" = BREAKFAST,
	"CLOTH" = CLOTH,
	"DAIRY" = DAIRY,
	"FRIED" = FRIED,
	"FRUIT" = FRUIT,
	"GORE" = GORE,
	"GRAIN" = GRAIN,
	"GROSS" = GROSS,
	"JUNKFOOD" = JUNKFOOD,
	"MEAT" = MEAT,
	"PINEAPPLE" = PINEAPPLE,
	"RAW" = RAW,
	"SUGAR" = SUGAR,
	"TOXIC" = TOXIC,
	"VEGETABLES" = VEGETABLES,
))

DEFINE_BITFIELD(toxic_foodtypes, list(
	"ALCOHOL" = ALCOHOL,
	"BREAKFAST" = BREAKFAST,
	"CLOTH" = CLOTH,
	"DAIRY" = DAIRY,
	"FRIED" = FRIED,
	"FRUIT" = FRUIT,
	"GORE" = GORE,
	"GRAIN" = GRAIN,
	"GROSS" = GROSS,
	"JUNKFOOD" = JUNKFOOD,
	"MEAT" = MEAT,
	"PINEAPPLE" = PINEAPPLE,
	"RAW" = RAW,
	"SUGAR" = SUGAR,
	"TOXIC" = TOXIC,
	"VEGETABLES" = VEGETABLES,
))

DEFINE_BITFIELD(pass_flags, list(
	"LETPASSTHROW" = LETPASSTHROW,
	"PASSBLOB" = PASSBLOB,
	"PASSCLOSEDTURF" = PASSCLOSEDTURF,
	"PASSFOAM" = PASSFOAM,
	"PASSGRILLE" = PASSGRILLE,
	"PASSMOB" = PASSMOB,
	"PASSTABLE" = PASSTABLE,
	"PASSTRANSPARENT" = PASSTRANSPARENT
))

DEFINE_BITFIELD(movement_type, list(
	"FLYING" = FLYING,
	"FLOATING" = FLOATING,
	"GROUND" = GROUND,
	"PHASING" = PHASING,
	"UPSIDE_DOWN" = UPSIDE_DOWN,
	"VENTCRAWLING" = VENTCRAWLING,
))

DEFINE_BITFIELD(mat_container_flags, list(
	"MATCONTAINER_EXAMINE" = MATCONTAINER_EXAMINE,
	"MATCONTAINER_NO_INSERT" = MATCONTAINER_NO_INSERT,
	"MATCONTAINER_ANY_INTENT"	= MATCONTAINER_ANY_INTENT,
	"MATCONTAINER_SILENT" = MATCONTAINER_SILENT,
	"BREAKDOWN_ALLOYS" = BREAKDOWN_ALLOYS,
))

DEFINE_BITFIELD(resistance_flags, list(
	"LAVA_PROOF" = LAVA_PROOF,
	"FIRE_PROOF" = FIRE_PROOF,
	"FLAMMABLE" = FLAMMABLE,
	"ON_FIRE" = ON_FIRE,
	"UNACIDABLE" = UNACIDABLE,
	"ACID_PROOF" = ACID_PROOF,
	"INDESTRUCTIBLE" = INDESTRUCTIBLE,
	"FREEZE_PROOF" = FREEZE_PROOF
))

DEFINE_BITFIELD(tesla_flags, list(
	"TESLA_MOB_DAMAGE" = TESLA_MOB_DAMAGE,
	"TESLA_OBJ_DAMAGE" = TESLA_OBJ_DAMAGE,
	"TESLA_MOB_STUN" = TESLA_MOB_STUN,
	"TESLA_ALLOW_DUPLICATES" = TESLA_ALLOW_DUPLICATES,
	"TESLA_MACHINE_EXPLOSIVE" = TESLA_MACHINE_EXPLOSIVE,
))

DEFINE_BITFIELD(mobility_flags, list(
	"MOVE" = MOBILITY_MOVE,
	"STAND" = MOBILITY_STAND,
	"PICKUP" = MOBILITY_PICKUP,
	"USE" = MOBILITY_USE,
	"UI" = MOBILITY_UI,
	"STORAGE" = MOBILITY_STORAGE,
	"PULL" = MOBILITY_PULL,
))

DEFINE_BITFIELD(rad_flags, list(
	"RAD_PROTECT_CONTENTS" = RAD_PROTECT_CONTENTS,
	"RAD_NO_CONTAMINATE" = RAD_NO_CONTAMINATE,
))

DEFINE_BITFIELD(vis_flags, list(
	"VIS_INHERIT_ICON" = VIS_INHERIT_ICON,
	"VIS_INHERIT_ICON_STATE" = VIS_INHERIT_ICON_STATE,
	"VIS_INHERIT_DIR" = VIS_INHERIT_DIR,
	"VIS_INHERIT_LAYER" = VIS_INHERIT_LAYER,
	"VIS_INHERIT_PLANE" = VIS_INHERIT_PLANE,
	"VIS_INHERIT_ID" = VIS_INHERIT_ID,
	"VIS_HIDE" = VIS_HIDE,
	"VIS_UNDERLAY" = VIS_UNDERLAY,
))

DEFINE_BITFIELD(z_flags, list(
	"Z_BLOCK_IN_UP" = Z_BLOCK_IN_UP,
	"Z_BLOCK_IN_DOWN" = Z_BLOCK_IN_DOWN,
	"Z_BLOCK_OUT_UP" = Z_BLOCK_OUT_UP,
	"Z_BLOCK_OUT_DOWN" = Z_BLOCK_OUT_DOWN,
	"Z_MIMIC_BELOW" = Z_MIMIC_BELOW,
	"Z_MIMIC_OVERWRITE" = Z_MIMIC_OVERWRITE,
	"Z_MIMIC_NO_OCCLUDE" = Z_MIMIC_NO_OCCLUDE,
	"Z_MIMIC_BASETURF" = Z_MIMIC_BASETURF,
))

DEFINE_BITFIELD(zmm_flags, list(
	"ZMM_IGNORE" = ZMM_IGNORE,
	"ZMM_MANGLE_PLANES" = ZMM_MANGLE_PLANES,
	"ZMM_LOOKAHEAD" = ZMM_LOOKAHEAD,
	"ZMM_AUTOMANGLE" = ZMM_AUTOMANGLE,
))

DEFINE_BITFIELD(trauma_flags, list(
	"SPECIAL_CURE_PROOF" = TRAUMA_SPECIAL_CURE_PROOF,
	"CLONEABLE" = TRAUMA_CLONEABLE,
	"NOT_RANDOM" = TRAUMA_NOT_RANDOM,
))

DEFINE_BITFIELD(internal_damage, list(
	"MECHA_INT_FIRE" = MECHA_INT_FIRE,
	"MECHA_INT_TEMP_CONTROL" = MECHA_INT_TEMP_CONTROL,
	"MECHA_INT_TANK_BREACH"	= MECHA_INT_TANK_BREACH,
	"MECHA_INT_CONTROL_LOST" = MECHA_INT_CONTROL_LOST,
))

DEFINE_BITFIELD(mecha_flags, list(
	"ADDING_ACCESS_POSSIBLE" = ADDING_ACCESS_POSSIBLE,
	"ADDING_MAINT_ACCESS_POSSIBLE" = ADDING_MAINT_ACCESS_POSSIBLE,
	"CANSTRAFE"	= CANSTRAFE,
	"LIGHTS_ON" = LIGHTS_ON,
	"SILICON_PILOT" = SILICON_PILOT,
	"IS_ENCLOSED" = IS_ENCLOSED,
	"HAS_LIGHTS" = HAS_LIGHTS,
))

DEFINE_BITFIELD(mob_biotypes, list(
	"MOB_BEAST" = MOB_BEAST,
	"MOB_BUG" = MOB_BUG,
	"MOB_EPIC" = MOB_EPIC, //megafauna
	"MOB_HUMANOID" = MOB_HUMANOID,
	"MOB_INORGANIC" = MOB_INORGANIC,
	"MOB_ORGANIC" = MOB_ORGANIC,
	"MOB_REPTILE" = MOB_REPTILE,
	"MOB_ROBOTIC" = MOB_ROBOTIC,
	"MOB_SPIRIT" = MOB_SPIRIT,
	"MOB_UNDEAD" = MOB_UNDEAD,
))

DEFINE_BITFIELD(emote_flags, list(
	"EMOTE_ANIMATED" = EMOTE_ANIMATED,
	"EMOTE_AUDIBLE" = EMOTE_AUDIBLE,
	"EMOTE_IMPORTANT" = EMOTE_IMPORTANT,
	"EMOTE_VISIBLE" = EMOTE_VISIBLE,
))

DEFINE_BITFIELD(machine_stat, list(
	"BROKEN" = BROKEN,
	"NOPOWER" = NOPOWER,
	"MAINT" = MAINT,
	"EMPED" = EMPED,
	"OVERHEATED" = OVERHEATED,
	"TURNED_OFF" = TURNED_OFF,
))

DEFINE_BITFIELD(disease_flags, list(
	"CURABLE" = CURABLE,
	"CAN_CARRY" = CAN_CARRY,
	"CAN_RESIST" = CAN_RESIST,
))

DEFINE_BITFIELD(spread_flags, list(
	"DISEASE_SPREAD_AIRBORNE" = DISEASE_SPREAD_AIRBORNE,
	"DISEASE_SPREAD_BLOOD" = DISEASE_SPREAD_BLOOD,
	"DISEASE_SPREAD_CONTACT_FLUIDS" = DISEASE_SPREAD_CONTACT_FLUIDS,
	"DISEASE_SPREAD_CONTACT_SKIN" = DISEASE_SPREAD_CONTACT_SKIN,
	"DISEASE_SPREAD_FALTERED" = DISEASE_SPREAD_FALTERED,
	"DISEASE_SPREAD_NON_CONTAGIOUS" = DISEASE_SPREAD_NON_CONTAGIOUS,
	"DISEASE_SPREAD_SPECIAL" = DISEASE_SPREAD_SPECIAL,
))

DEFINE_BITFIELD(infectable_biotypes, list(
	"MOB_BEAST" = MOB_BEAST,
	"MOB_BUG" = MOB_BUG,
	"MOB_EPIC" = MOB_EPIC, //megafauna
	"MOB_HUMANOID" = MOB_HUMANOID,
	"MOB_INORGANIC" = MOB_INORGANIC,
	"MOB_ORGANIC" = MOB_ORGANIC,
	"MOB_REPTILE" = MOB_REPTILE,
	"MOB_ROBOTIC" = MOB_ROBOTIC,
	"MOB_SPIRIT" = MOB_SPIRIT,
	"MOB_UNDEAD" = MOB_UNDEAD,
))
