import { Section } from 'tgui/components';

import { useBackend } from '../backend';
import { Window } from '../layouts';

export const BillingChangelog = (props) => {
  const { act, data } = useBackend();

  return (
    <Window width={700} height={550} scrollable theme="generic">
      <Window.Content>
        <Section title="Experimental Billing / Economy Changes" fill scrollable>
          <Section m={0.1} title="A Cold Universe">
            {
              "The universe is a cold place, but it's still not as cold as the corporations."
            }
            <br />
            {
              "It's every man for himself, fighting to wrap his fist around a few more credits. Everything has a price and you're going \
            to pay it, with your life if that's all you have."
            }
          </Section>

          <Section m={0.1} title="General Changes">
            {
              "You will find a new 'Billing Terminal' in every department head's office. These terminals\
            can be used to manage incoming and outgoing invoices."
            }
            <br /> <br />
            {
              "Invoices are created automatically by machines, and systems, but you can also manually create and send drafts to make custom bills.\
            Automatic invoices are generated on behlaf of institutions like Security, Engineering, and Service who provide an ongoing service to \
            the station's inhabitants."
            }
            <br /> <br />
            {
              "Some services require you to pay your bills, otherwise they will shutdown. This include bills generated by techfabs and APCs, which will \
            deny you service if you haven't paid your outstanding invoices. Your power will go out if you don't pay your bills."
            }
          </Section>

          <Section m={0.1} title="Drafts">
            {
              "As discussed above, billing terminals allow you to draft and send your own custom bills to any other department. Drafts are \
            the main method for monetizing your department's efforts."
            }
            <br /> <br />
            {
              'Medical can send bills to Science after they fix up a haphazard scientist, and refuse any other scientists service until the \
            bill is paid.'
            }
          </Section>
        </Section>
      </Window.Content>
    </Window>
  );
};
