Administration:
- code/modules/admin/**/*

Config Update:
- config/**/*

GitHub:
- .github/**/*

mapping:
- _maps/**/*

sound:
- sound/**/*

sprites:
- icons/**/*.dmi

sql:
- SQL/**/*

tools:
- tools/**/*

TGUI-Changes:
- tgui/**/*
