///List of all the gases, used in labelling the canisters
GLOBAL_LIST_INIT(gas_id_to_canister, sort_list(list(
	"Nitrogen" = /obj/machinery/portable_atmospherics/canister/nitrogen,
	"Oxygen" = /obj/machinery/portable_atmospherics/canister/oxygen,
	"Carbon Dioxide" = /obj/machinery/portable_atmospherics/canister/carbon_dioxide,
	"Plasma" = /obj/machinery/portable_atmospherics/canister/plasma,
	"Nitrous Oxide" = /obj/machinery/portable_atmospherics/canister/nitrous_oxide,
	"Nitrium" = /obj/machinery/portable_atmospherics/canister/nitrium,
	"Bz" = /obj/machinery/portable_atmospherics/canister/bz,
	"Air" = /obj/machinery/portable_atmospherics/canister/air,
	"Water Vapor" = /obj/machinery/portable_atmospherics/canister/water_vapor,
	"Tritium" = /obj/machinery/portable_atmospherics/canister/tritium,
	"Hyper-Noblium" = /obj/machinery/portable_atmospherics/canister/hyper_noblium,
	"Pluoxium" = /obj/machinery/portable_atmospherics/canister/pluoxium,
	"Caution" = /obj/machinery/portable_atmospherics/canister,
	"Freon" = /obj/machinery/portable_atmospherics/canister/freon,
	"Hydrogen" = /obj/machinery/portable_atmospherics/canister/hydrogen,
	"Healium" = /obj/machinery/portable_atmospherics/canister/healium,
	"Proto-Nitrate" = /obj/machinery/portable_atmospherics/canister/proto_nitrate,
	"Zauker" = /obj/machinery/portable_atmospherics/canister/zauker,
	"Helium" = /obj/machinery/portable_atmospherics/canister/helium,
	"Anti-Noblium" = /obj/machinery/portable_atmospherics/canister/antinoblium,
	"Halon" = /obj/machinery/portable_atmospherics/canister/halon,
)))
