// This proc is only used in `PDApainter.dm`, but for better readability, it's declared as global proc and stored here.
// This returns a card icon style by given job name. Check `card.dmi` for the card list.
/proc/get_cardstyle_by_jobname(jobname)
	if(!jobname)
		CRASH("The proc has taken a null value")

	var/static/id_style = list(
		// Command
		"Command (Custom)" = "captain",
		JOB_KEY_CAPTAIN = "captain",
		"Acting Captain" = "captain",
		// Service
		"Service (Custom)" = "rawservice",
		JOB_KEY_HEADOFPERSONNEL = "hop",
		JOB_KEY_ASSISTANT = "id",
		JOB_KEY_BOTANIST = "serv",
		JOB_KEY_BARTENDER = "serv",
		JOB_KEY_COOK = "serv",
		JOB_KEY_JANITOR = "janitor",
		JOB_KEY_CURATOR = "chap",
		JOB_KEY_CHAPLAIN = "chap",
		JOB_KEY_LAWYER = "lawyer",
		JOB_KEY_CLOWN = "clown",
		JOB_KEY_MIME = "mime",
		JOB_KEY_STAGEMAGICIAN = "serv",
		JOB_KEY_BARBER = "serv",
		// Cargo
		"Cargo (Custom)" = "rawcargo",
		JOB_KEY_QUARTERMASTER = "qm",
		JOB_KEY_CARGOTECHNICIAN = "cargo",
		JOB_KEY_SHAFTMINER = "miner",
		// R&D
		"Science (Custom)" = "rawscience",
		JOB_KEY_RESEARCHDIRECTOR = "rd",
		JOB_KEY_SCIENTIST = "sci",
		JOB_KEY_ROBOTICIST = "roboticist",
		JOB_KEY_EXPLORATIONCREW = "exploration",
		// Engineering
		"Engineering (Custom)" = "rawengineering",
		JOB_KEY_CHIEFENGINEER = "ce",
		JOB_KEY_STATIONENGINEER = "engi",
		JOB_KEY_ATMOSPHERICTECHNICIAN = "atmos",
		// Medical
		"Medical (Custom)" = "rawmedical",
		JOB_KEY_CHIEFMEDICALOFFICER = "cmo",
		JOB_KEY_MEDICALDOCTOR = "med",
		JOB_KEY_PARAMEDIC = "paramed",
		JOB_KEY_VIROLOGIST = "viro",
		JOB_KEY_GENETICIST = "gene",
		JOB_KEY_CHEMIST = "chemist",
		JOB_KEY_PSYCHIATRIST = "med",
		// Security
		"Security (Custom)" = "rawsecurity",
		JOB_KEY_HEADOFSECURITY = "hos",
		JOB_KEY_WARDEN = "warden",
		JOB_KEY_SECURITYOFFICER = "sec",
		JOB_KEY_DETECTIVE = "detective",
		JOB_KEY_BRIGPHYSICIAN = "brigphys",
		JOB_KEY_DEPUTY = "deputy",
		// ETC
		JOB_UNASSIGNED = "id",
		JOB_KEY_PRISONER = "orange",
		// EMAG
		"CentCom (Custom)" = "centcom",
		"CentCom" = "centcom",
		"ERT" = "ert",
		JOB_KEY_VIP = "gold",
		JOB_KEY_KING = "gold",
		"Syndicate Agent" = "syndicate",
		"Clown Operative" = "clown_op",
		"Unknown" = "unknown",
		// ETC2
		"Ratvar" = "ratvar"
	)
	return id_style[jobname] || "noname" // default: a card with no shape

// This returns a hud icon (from `hud.dmi`) by given job name.
// Some custom title is from `PDApainter.dm`. You neec to check it if you're going to remove custom job.
/proc/get_hud_by_jobkey(jobname, returns_unknown=TRUE)
	if(!jobname)
		CRASH("The proc has taken a null value")

	var/static/id_to_hud = list(
		// Command
		"Command (Custom)" = JOB_HUD_RAWCOMMAND,
		JOB_KEY_CAPTAIN = JOB_HUD_CAPTAIN,
		"Acting Captain" = JOB_HUD_ACTINGCAPTAIN ,

		// Service
		"Service (Custom)" = JOB_HUD_RAWSERVICE,
		JOB_KEY_HEADOFPERSONNEL = JOB_HUD_HEADOFPERSONNEL,
		JOB_KEY_ASSISTANT = JOB_HUD_ASSISTANT,
		JOB_KEY_BARTENDER = JOB_HUD_BARTENDER,
		JOB_KEY_COOK = JOB_HUD_COOK,
		JOB_KEY_BOTANIST = JOB_HUD_BOTANIST,
		JOB_KEY_CURATOR = JOB_HUD_CURATOR,
		JOB_KEY_CHAPLAIN = JOB_HUD_CHAPLAIN,
		JOB_KEY_JANITOR = JOB_HUD_JANITOR,
		JOB_KEY_LAWYER = JOB_HUD_LAWYER,
		JOB_KEY_MIME = JOB_HUD_MIME,
		JOB_KEY_CLOWN = JOB_HUD_CLOWN,
		JOB_KEY_STAGEMAGICIAN = JOB_HUD_STAGEMAGICIAN,
		JOB_KEY_BARBER = JOB_HUD_BARBER,

		// Cargo
		"Cargo (Custom)" = JOB_HUD_RAWCARGO,
		JOB_KEY_QUARTERMASTER = JOB_HUD_QUARTERMASTER,
		JOB_KEY_CARGOTECHNICIAN = JOB_HUD_CARGOTECHNICIAN,
		JOB_KEY_SHAFTMINER = JOB_HUD_SHAFTMINER,

		// R&D
		"Science (Custom)" = JOB_HUD_RAWSCIENCE,
		JOB_KEY_RESEARCHDIRECTOR = JOB_HUD_RESEARCHDIRECTOR,
		JOB_KEY_SCIENTIST = JOB_HUD_SCIENTIST,
		JOB_KEY_ROBOTICIST = JOB_HUD_ROBOTICIST,
		JOB_KEY_EXPLORATIONCREW = JOB_HUD_EXPLORATIONCREW,

		// Engineering
		"Engineering (Custom)" = JOB_HUD_RAWENGINEERING,
		JOB_KEY_CHIEFENGINEER = JOB_HUD_CHIEFENGINEER,
		JOB_KEY_STATIONENGINEER = JOB_HUD_STATIONENGINEER,
		JOB_KEY_ATMOSPHERICTECHNICIAN = JOB_HUD_ATMOSPHERICTECHNICIAN,

		// Medical
		"Medical (Custom)" = JOB_HUD_RAWMEDICAL,
		JOB_KEY_CHIEFMEDICALOFFICER = JOB_HUD_CHEIFMEDICALOFFICIER,
		JOB_KEY_MEDICALDOCTOR = JOB_HUD_MEDICALDOCTOR,
		JOB_KEY_PARAMEDIC = JOB_HUD_PARAMEDIC,
		JOB_KEY_VIROLOGIST = JOB_HUD_VIROLOGIST,
		JOB_KEY_CHEMIST = JOB_HUD_CHEMIST,
		JOB_KEY_GENETICIST = JOB_HUD_GENETICIST,
		JOB_KEY_PSYCHIATRIST = JOB_HUD_PSYCHIATRIST,

		// Security
		"Security (Custom)" = JOB_HUD_RAWSECURITY,
		JOB_KEY_HEADOFSECURITY = JOB_HUD_HEADOFSECURITY,
		JOB_KEY_SECURITYOFFICER = JOB_HUD_SECURITYOFFICER,
		JOB_KEY_WARDEN = JOB_HUD_WARDEN,
		JOB_KEY_DETECTIVE = JOB_HUD_DETECTIVE,
		JOB_KEY_BRIGPHYSICIAN = JOB_HUD_BRIGPHYSICIAN,
		JOB_KEY_DEPUTY = JOB_HUD_DEPUTY,

		// CentCom
		"CentCom (Custom)" = JOB_HUD_RAWCENTCOM,
		"CentCom" = JOB_HUD_CENTCOM,
		"ERT" = JOB_HUD_CENTCOM,

		// ETC
		JOB_KEY_VIP = JOB_HUD_VIP,
		JOB_KEY_KING = JOB_HUD_KING,
		"Syndicate Agent" = JOB_HUD_SYNDICATE,
		"Clown Operative" = JOB_HUD_SYNDICATE,
		JOB_UNASSIGNED = JOB_HUD_UNKNOWN,
		JOB_KEY_PRISONER = JOB_HUD_PRISONER
	)
	if(returns_unknown)
		return id_to_hud[jobname] || JOB_HUD_UNKNOWN // default: a grey unknown hud
	return id_to_hud[jobname] // this will return null

// used to determine chat color by HUD in `chatmessage.dm`
// Note: custom colors are what I really didn't put much attention into. feel free to change its color when you feel off.
/proc/get_chatcolor_by_hud(jobname)
	if(!jobname)
		CRASH("The proc has taken a null value")

	var/static/hud_to_chatcolor = list(
		// Command
		JOB_HUD_RAWCOMMAND = JOB_CHATCOLOR_RAWCOMMAND,
		JOB_HUD_CAPTAIN = JOB_CHATCOLOR_CAPTAIN,
		JOB_HUD_ACTINGCAPTAIN  = JOB_CHATCOLOR_ACTINGCAPTAIN,

		// Service
		JOB_HUD_RAWSERVICE = JOB_CHATCOLOR_RAWSERVICE,
		JOB_HUD_HEADOFPERSONNEL = JOB_CHATCOLOR_HEADOFPERSONNEL,
		JOB_HUD_ASSISTANT = JOB_CHATCOLOR_ASSISTANT,
		JOB_HUD_BARTENDER = JOB_CHATCOLOR_BARTENDER,
		JOB_HUD_COOK = JOB_CHATCOLOR_COOK,
		JOB_HUD_BOTANIST = JOB_CHATCOLOR_BOTANIST,
		JOB_HUD_CURATOR = JOB_CHATCOLOR_CURATOR,
		JOB_HUD_CHAPLAIN = JOB_CHATCOLOR_CHAPLAIN,
		JOB_HUD_JANITOR = JOB_CHATCOLOR_JANITOR,
		JOB_HUD_LAWYER = JOB_CHATCOLOR_LAWYER,
		JOB_HUD_MIME = JOB_CHATCOLOR_MIME,
		JOB_HUD_CLOWN = JOB_CHATCOLOR_CLOWN,
		JOB_HUD_STAGEMAGICIAN = JOB_CHATCOLOR_STAGEMAGICIAN,
		JOB_HUD_BARBER = JOB_CHATCOLOR_BARBER,

		// Cargo
		JOB_HUD_RAWCARGO = JOB_CHATCOLOR_RAWCARGO,
		JOB_HUD_QUARTERMASTER = JOB_CHATCOLOR_QUARTERMASTER,
		JOB_HUD_CARGOTECHNICIAN = JOB_CHATCOLOR_CARGOTECHNICIAN,
		JOB_HUD_SHAFTMINER = JOB_CHATCOLOR_SHAFTMINER,

		// R&D
		JOB_HUD_RAWSCIENCE = JOB_CHATCOLOR_RAWSCIENCE,
		JOB_HUD_RESEARCHDIRECTOR = JOB_CHATCOLOR_RESEARCHDIRECTOR,
		JOB_HUD_SCIENTIST = JOB_CHATCOLOR_SCIENTIST,
		JOB_HUD_ROBOTICIST = JOB_CHATCOLOR_ROBOTICIST,
		JOB_HUD_EXPLORATIONCREW = JOB_CHATCOLOR_EXPLORATIONCREW,

		// Engineering
		JOB_HUD_RAWENGINEERING = JOB_CHATCOLOR_RAWENGINEERING,
		JOB_HUD_CHIEFENGINEER = JOB_CHATCOLOR_CHIEFENGINEER,
		JOB_HUD_STATIONENGINEER = JOB_CHATCOLOR_STATIONENGINEER,
		JOB_HUD_ATMOSPHERICTECHNICIAN = JOB_CHATCOLOR_ATMOSPHERICTECHNICIAN,

		// Medical
		JOB_HUD_RAWMEDICAL = JOB_CHATCOLOR_RAWMEDICAL,
		JOB_HUD_CHEIFMEDICALOFFICIER = JOB_CHATCOLOR_CHEIFMEDICALOFFICIER,
		JOB_HUD_MEDICALDOCTOR = JOB_CHATCOLOR_MEDICALDOCTOR,
		JOB_HUD_PARAMEDIC = JOB_CHATCOLOR_PARAMEDIC,
		JOB_HUD_VIROLOGIST = JOB_CHATCOLOR_VIROLOGIST,
		JOB_HUD_CHEMIST = JOB_CHATCOLOR_CHEMIST,
		JOB_HUD_GENETICIST = JOB_CHATCOLOR_GENETICIST,
		JOB_HUD_PSYCHIATRIST = JOB_CHATCOLOR_PSYCHIATRIST,

		// Security
		JOB_HUD_RAWSECURITY = JOB_CHATCOLOR_RAWSECURITY,
		JOB_HUD_HEADOFSECURITY = JOB_CHATCOLOR_HEADOFSECURITY,
		JOB_HUD_WARDEN = JOB_CHATCOLOR_WARDEN,
		JOB_HUD_SECURITYOFFICER = JOB_CHATCOLOR_SECURITYOFFICER,
		JOB_HUD_DETECTIVE = JOB_CHATCOLOR_DETECTIVE,
		JOB_HUD_BRIGPHYSICIAN = JOB_CHATCOLOR_BRIGPHYSICIAN,
		JOB_HUD_DEPUTY = JOB_CHATCOLOR_DEPUTY,

		// CentCom
		JOB_HUD_RAWCENTCOM = JOB_CHATCOLOR_RAWCENTCOM,
		JOB_HUD_CENTCOM = JOB_CHATCOLOR_CENTCOM,

		// ETC
		JOB_HUD_VIP = JOB_CHATCOLOR_VIP,
		JOB_HUD_KING = JOB_CHATCOLOR_KING,
		JOB_HUD_SYNDICATE = JOB_CHATCOLOR_SYNDICATE,
		JOB_HUD_NOTCENTCOM = JOB_CHATCOLOR_NOTCENTCOM,
		JOB_HUD_PRISONER = JOB_CHATCOLOR_PRISONER,
		JOB_HUD_UNKNOWN = JOB_CHATCOLOR_UNKNOWN
	)
	return hud_to_chatcolor[jobname] || JOB_CHATCOLOR_UNKNOWN

