// Weapon Categories
#define RND_CATEGORY_WEAPONS "/Weaponry"
#define RND_SUBCATEGORY_WEAPONS_PARTS "/Weapon Parts"
#define RND_SUBCATEGORY_WEAPONS_RANGED "/Ranged Weapons"
#define RND_SUBCATEGORY_WEAPONS_MELEE "/Melee Weapons"
#define RND_SUBCATEGORY_WEAPONS_EXPLOSIVES "/Explosives"
#define RND_SUBCATEGORY_WEAPONS_EXOSUIT "/Exosuit Weapons"
#define RND_CATEGORY_FIRING_PINS "/Weaponry/Firing Pins"
#define RND_CATEGORY_AMMO "/Weaponry/Ammunition"

// Wiremod Categories
#define RND_CATEGORY_CIRCUITRY "/Circuitry"
#define RND_SUBCATEGORY_CIRCUITRY_COMPONENTS "/Circuit Components"
#define RND_CATEGORY_CORE "/Circuitry/Core"
#define RND_CATEGORY_SHELLS "/Circuitry/Shells"
#define RND_CATEGORY_INPUT_COMPONENTS "/Circuitry/Input Components"
#define RND_CATEGORY_OUTPUT_COMPONENTS "/Circuitry/Output Components"
#define RND_CATEGORY_MATH_COMPONENTS "/Circuitry/Math Components"
#define RND_CATEGORY_TIME_COMPONENTS "/Circuitry/Time Components"
#define RND_CATEGORY_LOGIC_COMPONENTS "/Circuitry/Logic Components"
#define RND_CATEGORY_GATE_COMPONENTS "/Circuitry/Gate Components"
#define RND_CATEGORY_LIST_COMPONENTS "/Circuitry/List Components"
#define RND_CATEGORY_MEMORY_COMPONENTS "/Circuitry/Memory Components"
#define RND_CATEGORY_CONVERSION_COMPONENTS "/Circuitry/Conversion Components"
#define RND_CATEGORY_STRING_COMPONENTS "/Circuitry/String Components"
#define RND_CATEGORY_REFERENCE_COMPONENTS "/Circuitry/Reference Components"
#define RND_CATEGORY_BCI_COMPONENTS "/Circuitry/BCI Components"
#define RND_CATEGORY_TEMPLATES "/Circuitry/Professor's Circuits"

// Tool Categories
#define RND_CATEGORY_TOOLS "/Tools"
#define RND_SUBCATEGORY_TOOLS_MEDICAL "/Medical Tools"
#define RND_SUBCATEGORY_TOOLS_MEDICAL_ADVANCED "/Medical Tools (Advanced)"
#define RND_SUBCATEGORY_TOOLS_MEDICAL_ALIEN "/Medical Tools (Alien)"
#define RND_SUBCATEGORY_TOOLS_ENGINEERING "/Engineering Tools"
#define RND_SUBCATEGORY_TOOLS_ENGINEERING_ADVANCED "/Engineering Tools (Advanced)"
#define RND_SUBCATEGORY_TOOLS_ENGINEERING_ALIEN "/Engineering Tools (Alien)"
#define RND_SUBCATEGORY_TOOLS_BOTANY "/Botany Tools"
#define RND_SUBCATEGORY_TOOLS_JANITORIAL "/Janitorial Tools"
#define RND_SUBCATEGORY_TOOLS_PLUMBING "/Plumbing Tools"
#define RND_SUBCATEGORY_TOOLS_ATMOSPHERICS "/Atmospherics Tools"
#define RND_SUBCATEGORY_TOOLS_MISC "/Miscellaneous Tools"
#define RND_CATEGORY_TOOL_DESIGNS "/Tools"

// Building categories
#define RND_CATEGORY_CONSTRUCTION "/Construction"
#define RND_SUBCATEGORY_CONSTRUCTION_MOUNTS "/Frames & Mounts"
#define RND_SUBCATEGORY_CONSTRUCTION_MACHINERY "/Machinery"
#define RND_SUBCATEGORY_CONSTRUCTION_LIGHTING "/Lighting"

// Computer categories
#define RND_SUBCATEGORY_COMPUTER_ENTERTAINMENT "/Service Consoles"
#define RND_SUBCATEGORY_COMPUTER_MEDICAL "/Medical Consoles"
#define RND_SUBCATEGORY_COMPUTER_ROBOTICS "/Robotics Consoles"
#define RND_SUBCATEGORY_COMPUTER_GENETICS "/Genetics Consoles"
#define RND_SUBCATEGORY_COMPUTER_RECORDS "/Records Consoles"
#define RND_SUBCATEGORY_COMPUTER_COMMAND "/Command Consoles"
#define RND_SUBCATEGORY_COMPUTER_SECURITY "/Security Consoles"
#define RND_SUBCATEGORY_COMPUTER_RESEARCH "/Research Consoles"
#define RND_SUBCATEGORY_COMPUTER_ENGINEERING "/Engineering & Atmospherics Consoles"
#define RND_SUBCATEGORY_COMPUTER_CARGO "/Cargo Consoles"
#define RND_SUBCATEGORY_COMPUTER_TELECOMMS "/Telecommunications Consoles"
#define RND_CATEGORY_COMPUTER_BOARDS "/Computer Boards"

// Machine categories
#define RND_CATEGORY_MACHINE "/Machine Boards"
#define RND_SUBCATEGORY_MACHINE_KITCHEN "/Kitchen Machines"
#define RND_SUBCATEGORY_MACHINE_BAR "/Bar Machines"
#define RND_SUBCATEGORY_MACHINE_ENGINEERING "/Engineering Machines"
#define RND_SUBCATEGORY_MACHINE_SECURITY "/Security Machines"
#define RND_SUBCATEGORY_MACHINE_CARGO "/Cargo Machines"
#define RND_SUBCATEGORY_MACHINE_FAB "/Fabricators"
#define RND_SUBCATEGORY_MACHINE_SERVICE "/Service Machines"
#define RND_CATEGORY_MACHINERY "/Machine Boards"
#define RND_CATEGORY_SHUTTLE_MACHINERY "/Machine Boards/Shuttle Machines"
#define RND_CATEGORY_ENGINEERING_MACHINERY "/Machine Boards/Engineering Machines"
#define RND_CATEGORY_SUBSPACE_TELECOMMS "/Machine Boards/Telecommunications Machines"
#define RND_CATEGORY_TELEPORTATION_MACHINERY "/Machine Boards/Teleportation Machines"
#define RND_CATEGORY_RESEARCH_MACHINERY "/Machine Boards/Research Machines"
#define RND_CATEGORY_MEDICAL_MACHINERY "/Machine Boards/Medical Machines"
#define RND_CATEGORY_HYDROPONICS_MACHINERY "/Machine Boards/Botany Machines"

// Equipment categories, a lot of things classify inside here
#define RND_CATEGORY_EQUIPMENT "/Equipment"
#define RND_SUBCATEGORY_EQUIPMENT_SERVICE "/Service Equipment"
#define RND_SUBCATEGORY_EQUIPMENT_MEDICAL "/Medical Equipment"
#define RND_SUBCATEGORY_EQUIPMENT_SECURITY "/Security Equipment"
#define RND_SUBCATEGORY_EQUIPMENT_BLUESPACE "/Bluespace Equipment"
#define RND_SUBCATEGORY_EQUIPMENT_ENGINEERING "/Engineering Equipment"
#define RND_SUBCATEGORY_EQUIPMENT_ATMOSPHERICS "/Atmospherics Equipment"
#define RND_SUBCATEGORY_EQUIPMENT_SCIENCE "/Science Equipment"
#define RND_SUBCATEGORY_EQUIPMENT_GAS_TANKS "/Gas Tanks"
#define RND_SUBCATEGORY_EQUIPMENT_JANITOR "/Janitorial Equipment"
#define RND_SUBCATEGORY_EQUIPMENT_MISC "/Miscellaneous Equipment"
#define RND_CATEGORY_BLUESPACE_DESIGNS "/Equipment/Bluespace Equipment"
#define RND_CATEGORY_ELECTRONICS "/Construction/Electronics"

// AI categories, the AI is usually malf, but in this case it helped me
#define RND_CATEGORY_AI "/Artificial Intelligence"
#define RND_SUBCATEGORY_AI_CORE "/AI Construction"
#define RND_SUBCATEGORY_AI_LAW_MANIPULATION "/AI Law Manipulation"
#define RND_SUBCATEGORY_AI_CORE_MODULES "/Core AI Modules"
#define RND_SUBCATEGORY_AI_DANGEROUS_MODULES "/Dangerous AI Modules"

// Modular computer categories
#define RND_CATEGORY_MODULAR_COMPUTERS "/Modular Computers"
#define RND_SUBCATEGORY_MODULAR_COMPUTERS_FRAMES "/Frames"

// Stock Parts/Upgraded categories
#define RND_CATEGORY_STOCK_PARTS "/Stock Parts"
#define RND_SUBCATEGORY_STOCK_PARTS_TELECOMMS "/Telecommunications Parts"
#define RND_SUBCATEGORY_STOCK_PARTS_1 "/Tier 1 Parts"
#define RND_SUBCATEGORY_STOCK_PARTS_2 "/Tier 2 Parts"
#define RND_SUBCATEGORY_STOCK_PARTS_3 "/Tier 3 Parts"
#define RND_SUBCATEGORY_STOCK_PARTS_4 "/Tier 4 Parts"
#define RND_SUBCATEGORY_STOCK_PARTS_EXCHANGERS "/Exchange Devices"

// Exosuit Boards, used to make mechs
#define RND_CATEGORY_EXOSUIT_BOARDS "/Exosuit Boards"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_RIPLEY "/Ripley"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_ODYSSEUS "/Odysseus"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_GYGAX "/Gygax"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_DURAND "/Durand"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_HONK "/H.O.N.K."
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_PHAZON "/Phazon"
#define RND_SUBCATEGORY_EXOSUIT_BOARDS_CLARKE "/Clarke"
// #define RND_SUBCATEGORY_EXOSUIT_BOARDS_SAVANNAH_IVANOV "/Savannah-Ivanov" this one isn't technically in-game, yet construction_paths.dm has it

// Exosuits themselves, not the boards
#define RND_CATEGORY_RIPLEY "/Ripley"
#define RND_CATEGORY_ODYSSEUS "/Odysseus"
#define RND_CATEGORY_GYGAX "/Gygax"
#define RND_CATEGORY_DURAND "/Durand"
#define RND_CATEGORY_HONK "/H.O.N.K."
#define RND_CATEGORY_PHAZON "/Phazon"
#define RND_CATEGORY_CLARKE "/Clarke"
#define RND_SUBCATEGORY_MECHFAB_CHASSIS "/Chassis"
#define RND_SUBCATEGORY_MECHFAB_SUPPORTED_EQUIPMENT "/Supported Equipment"

// Exosuit equipment, everything a mech can have inside
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_MINING "/Mining Equipment"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_WEAPONS "/Weapons & Ammunition"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_MODULES "/Armor & Repair Modules"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_MISC "/Miscellaneous"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_MEDICAL "/Medical"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_HONK "/Clown Designs"
#define RND_SUBCATEGORY_MECHFAB_EQUIPMENT_CONTROL_INTERFACES "/Control Interfaces"
#define RND_CATEGORY_EXOSUIT_EQUIPMENT "/Exosuit Equipment"
#define RND_CATEGORY_EXOSUIT_AMMUNITION "/Exosuit Equipment/Weapons & Ammunition"

// Cyborg category
#define RND_CATEGORY_MECHFAB_CYBORG "/Cyborg"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_CHASSIS "/Cyborg Chassis"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_COMPONENTS "/Components"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_CONTROL_INTERFACES "/Control Interfaces"
#define RND_CATEGORY_CYBORG "/Cyborg"

// Cyborg modules category ¿
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_ALL "/All Cyborgs"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_MEDICAL "/Medical Cyborgs"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_ENGINEERING "/Engineering Cyborgs"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_JANITOR "/Janitorial Cyborgs"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_MINING "/Mining Cyborgs"
#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_SERVICE "/Service Cyborgs"
#define RND_CATEGORY_CYBORG_UPGRADE_MODULES "/Cyborg Modules"

// Modsuit Plating/Building category
#define RND_CATEGORY_MODSUITS "/MOD Suits"
#define RND_SUBCATEGORY_MODUITS_CHASSIS "/Chassis"
#define RND_SUBCATEGORY_MODSUITS_PLATING "/Plating"
#define RND_SUBCATEGORY_MODSUITS_MISC "/Misc"

// Modsuit Modules
#define RND_SUBCATEGORY_MODSUIT_MODULES_GENERAL "/General Modules"
#define RND_SUBCATEGORY_MODSUIT_MODULES_ENGINEERING "/Engineering Modules"
#define RND_SUBCATEGORY_MODSUIT_MODULES_MEDICAL "/Medical Modules"
#define RND_SUBCATEGORY_MODSUIT_MODULES_SCIENCE "/Science Modules"
#define RND_SUBCATEGORY_MODSUIT_MODULES_SECURITY "/Security Modules"
#define RND_SUBCATEGORY_MODSUIT_MODULES_SUPPLY "/Supply Modules"
#define RND_SUBCATEGORY_MODSUIT_MODULES_SERVICE "/Service Modules"
#define RND_CATEGORY_MOD_CONSTRUCTION "/MOD Suits"
#define RND_CATEGORY_MOD_MODULES "/MOD Modules"

// Cybernetics, used by exofab and medical lathe
#define RND_CATEGORY_CYBERNETICS "/Cybernetics"
#define RND_SUBCATEGORY_CYBERNETICS_ORGANS "/Cybernetic Organs"
#define RND_SUBCATEGORY_CYBERNETICS_IMPLANTS "/Cybernetic Implants"

// Implants, can be printed by exofab and medical lathe
#define RND_CATEGORY_IMPLANTS "/Cybernetics/Cybernetic Implants"
#define RND_CATEGORY_IPC_COMPONENTS "/Cybernetics/IPC Components"

// Limb Categories
#define RND_CATEGORY_DIGITIGRADE "digitigrade"
#define RND_CATEGORY_OTHER "other"

/// Biogenerator Categories
#define RND_CATEGORY_FOOD "Food"
#define RND_CATEGORY_BOTANY_CHEMICALS "Botany Chemicals"
#define RND_CATEGORY_ORGANIC_MATERIALS "Organic Materials"

// Meta categories
#define RND_CATEGORY_INITIAL "initial"
#define RND_CATEGORY_HACKED "hacked"
#define RND_CATEGORY_IMPORTED "/Imported Designs"

#define RND_CATEGORY_UTILITY_NANITES "Utility Nanites"
#define RND_CATEGORY_MEDICAL_NANITES "Medical Nanites"
#define RND_CATEGORY_AUGMENTATION_NANITES "Augmentation Nanites"
#define RND_CATEGORY_DEFECTIVE_NANITES "Defective Nanites"
#define RND_CATEGORY_WEAPONIZED_NANITES "Weaponized Nanites"
#define RND_CATEGORY_SUPPRESSION_NANITES "Suppression Nanites"
#define RND_CATEGORY_SENSOR_NANITES "Sensor Nanites"
#define RND_CATEGORY_PROTOCOL_NANITES "Protocol Nanites"

// Very specific categories, some items have one or more categories they fit inside such as a basic power cell
#define RND_CATEGORY_MEDICAL "/Medical Designs"
#define RND_CATEGORY_SECURITY "/Security Designs"
#define RND_SUBCATEGORY_SECURITY_AMMO "/Ammunition"
#define RND_SUBCATEGORY_SECURITY_WEAPON_PARTS "/Weapon Parts"
#define RND_SUBCATEGORY_SECURITY_GEAR "/Restraints & Gear"
#define RND_CATEGORY_TELECOMMS "/T-Comm Designs"
#define RND_CATEGORY_MEDICAL_DESIGNS "/Medical Designs"
#define RND_SUBCATEGORY_MEDICAL_CHEMISTRY "/Chemistry Supplies"
#define RND_SUBCATEGORY_MEDICAL_TOOLS "/Medical Tools"
#define RND_SUBCATEGORY_MEDICAL_IMPLANT_CASES "/Implant Cases"
#define RND_CATEGORY_POWER_DESIGNS "/Power Designs"
#define RND_CATEGORY_MINING_DESIGNS "/Mining Designs"
#define RND_SUBCATEGORY_MINING_TOOLS "/Mining Tools"
#define RND_SUBCATEGORY_MINING_KA_MODS "/Kinetic Accelerator Mods"
#define RND_SUBCATEGORY_MINING_SUPPLY "/Supply Equipment"
#define RND_CATEGORY_COMPUTER_PARTS "/Modular Computers/Parts"
#define RND_CATEGORY_MISC "/Miscellaneous"
#define RND_SUBCATEGORY_MISC_ASSEMBLIES "/Electrical Assemblies"
#define RND_SUBCATEGORY_MISC_MEDIA "/Recording & Media"
#define RND_SUBCATEGORY_MISC_TILES "/Floor Tiles"
#define RND_SUBCATEGORY_MISC_TOYS "/Toys & Novelties"
#define RND_SUBCATEGORY_MISC_SUPPLY "/Supply & Vending"
#define RND_CATEGORY_MATERIAL "/Construction/Materials & Alloys"
#define RND_CATEGORY_DINNERWARE "/Miscellaneous/Dinnerware"
