#define ACHIEVEMENT_DEFAULT "default"
#define ACHIEVEMENT_SCORE "score"

//Misc Medal hub IDs
#define MEDAL_METEOR 			      "Your Life Before Your Eyes"
#define MEDAL_PULSE 		    	  "Jackpot"
#define MEDAL_TIMEWASTE 		      "Overextended The Joke"
#define MEDAL_RODSUPLEX 		      "Feat of Strength"
#define MEDAL_SINGULARITY_DEATH       "Crossing the Horizon" // get eaten by a singularity
#define MEDAL_GET_CLUWNED             "KILLMEKILLMEKILLME" // get turned into a vile creature known as a cluwne
#define MEDAL_USE_WEIGHT_MACHINE      "Survival of the Fittest"
#define MEDAL_UNWRENCH_HIGH_PRESSURE  "WHOOSH!"
#define MEDAL_COMPLETE_ALL_OBJECTIVES "Greentext"
#define MEDAL_APPLY_REAGENT_METH      "NYOOOOM"
#define MEDAL_APPLY_REAGENT_SOYMILK   "Soyboy"
#define MEDAL_15_AI_LAW_CHANGES       "Dave, my mind is going"
#define MEDAL_DETONATE_WELDERBOMB     "That was stupid of you."
#define MEDAL_SUCCUMB                 "Please just end the pain"
#define MEDAL_GHOSTS                  "G-G-Ghosts?"
#define MEDAL_CLOWNCARKING            "Round and Full"
#define MEDAL_THANKSALOT              "The Best Driver"
#define MEDAL_ONEKHRS                 "Veteran"
#define MEDAL_TWOKHRS                 "Seasoned Veteran"
#define MEDAL_THREEKHRS               "Grilled Seasoned Veteran"
#define MEDAL_FOURKHRS                "Burnt Grilled Seasoned Veteran"
#define MEDAL_MINTGIB                 "Best Meal of My Life"
#define MEDAL_CHASMJAUNT              "Mind the Gap"
#define MEDAL_BIKE                    "This Lousy Achievement"
#define MEDAL_WAROPS                  "Play GLOBAL THERMONUCLEAR WAR"
#define MEDAL_DRUNK					  "Little Chickadee"

//Boss medals

// Medal hub IDs for boss medals (Pre-fixes)
#define BOSS_MEDAL_ANY		  "Boss Killer"
#define BOSS_MEDAL_MINER	  "Blood-drunk Miner Killer"
#define BOSS_MEDAL_BUBBLEGUM  "Bubblegum Killer"
#define BOSS_MEDAL_COLOSSUS	  "Colossus Killer"
#define BOSS_MEDAL_DRAKE	  "Drake Killer"
#define BOSS_MEDAL_HIEROPHANT "Hierophant Killer"
#define BOSS_MEDAL_LEGION	  "Legion Killer"
#define BOSS_MEDAL_TENDRIL	  "Tendril Exterminator"
#define BOSS_MEDAL_SWARMERS   "Swarmer Beacon Killer"

#define BOSS_MEDAL_MINER_CRUSHER	  	"Blood-drunk Miner Crusher"
#define BOSS_MEDAL_BUBBLEGUM_CRUSHER  	"Bubblegum Crusher"
#define BOSS_MEDAL_COLOSSUS_CRUSHER	  	"Colossus Crusher"
#define BOSS_MEDAL_DRAKE_CRUSHER	  	"Drake Crusher"
#define BOSS_MEDAL_HIEROPHANT_CRUSHER 	"Hierophant Crusher"
#define BOSS_MEDAL_LEGION_CRUSHER	 	"Legion Crusher"
#define BOSS_MEDAL_SWARMERS_CRUSHER		"Swarmer Beacon Crusher"

// Medal hub IDs for boss-kill scores
#define BOSS_SCORE 	         "Bosses Killed"
#define MINER_SCORE 		 "BDMs Killed"
#define BUBBLEGUM_SCORE 	 "Bubblegum Killed"
#define COLOSSUS_SCORE 	     "Colossus Killed"
#define DRAKE_SCORE 	     "Drakes Killed"
#define HIEROPHANT_SCORE 	 "Hierophants Killed"
#define LEGION_SCORE 	     "Legion Killed"
#define SWARMER_BEACON_SCORE "Swarmer Beacs Killed"
#define TENDRIL_CLEAR_SCORE	 "Tendrils Killed"
