#define CDR_MOL_TO_SPIN 1000
#define CDR_SPIN_INSTABILITY_MULT 1e3
#define CDR_PARABOLIC_ACCURACY 1e4

#define CDR_BASE_INSTABILITY 100

#define CDR_HEAT_CONSUMED_PER_MOL 1 MEGAWATT
#define CDR_FLUX_TO_POWER 1 KILOWATT

#define CDR_MAX_CORE_HEALTH 250

#define CDR_CORE_MASS_DIV 1000

#define CDR_RADIO_COOLDOWN 8 SECONDS

#define CDR_HEALTH_DELTA_DIVISOR 4
