// station departments
#define DEPARTMENT_NAME_COMMAND "Command"
#define DEPARTMENT_BITFLAG_COMMAND (1<<0)
#define DEPARTMENT_NAME_CIVILIAN "Civilian"
#define DEPARTMENT_BITFLAG_CIVILIAN (1<<1)
#define DEPARTMENT_NAME_SERVICE "Service"
#define DEPARTMENT_BITFLAG_SERVICE (1<<2)
#define DEPARTMENT_NAME_CARGO "Cargo"
#define DEPARTMENT_BITFLAG_CARGO (1<<3)
#define DEPARTMENT_NAME_SCIENCE "Science"
#define DEPARTMENT_BITFLAG_SCIENCE (1<<4)
#define DEPARTMENT_NAME_ENGINEERING "Engineering"
#define DEPARTMENT_BITFLAG_ENGINEERING (1<<5)
#define DEPARTMENT_NAME_MEDICAL "Medical"
#define DEPARTMENT_BITFLAG_MEDICAL (1<<6)
#define DEPARTMENT_NAME_SECURITY "Security"
#define DEPARTMENT_BITFLAG_SECURITY (1<<7)
#define DEPARTMENT_NAME_VIP "VIP"
#define DEPARTMENT_BITFLAG_VIP (1<<8)
#define DEPARTMENT_NAME_SILICON "Silicon"
#define DEPARTMENT_BITFLAG_SILICON  (1<<9)
#define DEPARTMENT_NAME_UNASSIGNED "Misc"
#define DEPARTMENT_BITFLAG_UNASSIGNED (1<<10)

#define DEPARTMENT_NAME_CENTCOM "CentCom"
#define DEPT_BITFLAG_CENTCOM (1<<11)
#define DEPARTMENT_NAME_OTHER "Other"
#define DEPARTMENT_BITFLAG_OTHER (1<<12)

#define DEPT_BITFLAG_STATIONS (DEPARTMENT_BITFLAG_COMMAND + DEPARTMENT_BITFLAG_CIVILIAN + DEPARTMENT_BITFLAG_SERVICE + DEPARTMENT_BITFLAG_CARGO + DEPARTMENT_BITFLAG_SCIENCE + DEPARTMENT_BITFLAG_ENGINEERING + DEPARTMENT_BITFLAG_MEDICAL + DEPARTMENT_BITFLAG_SECURITY)

// not real department. These exist for pref grouping
#define DEPARTMENT_NAME_ASSISTANT "Assistant"
#define DEPARTMENT_NAME_CAPTAIN "Captain"

DEFINE_BITFIELD(departments_bitflags, list(
	"SECURITY" = DEPARTMENT_BITFLAG_SECURITY,
	"COMMAND" = DEPARTMENT_BITFLAG_COMMAND,
	"SERVICE" = DEPARTMENT_BITFLAG_SERVICE,
	"CARGO" = DEPARTMENT_BITFLAG_CARGO,
	"ENGINEERING" = DEPARTMENT_BITFLAG_ENGINEERING,
	"SCIENCE" = DEPARTMENT_BITFLAG_SCIENCE,
	"MEDICAL" = DEPARTMENT_BITFLAG_MEDICAL,
	"SILICON" = DEPARTMENT_BITFLAG_SILICON,
))


// Crew Manifest will show crew data in this order
// in favour of our downstreams, sort order is increased by 10, so that they can add anything between these (i.e NSV munition dept)
#define DEPT_MANIFEST_ORDER_COMMAND 10
#define DEPT_MANIFEST_ORDER_CENTCOM 13 // generally it won't be used
#define DEPT_MANIFEST_ORDER_VIP 16
#define DEPT_MANIFEST_ORDER_SECURITY 20
#define DEPT_MANIFEST_ORDER_ENGINEERING 30
#define DEPT_MANIFEST_ORDER_MEDICAL 40
#define DEPT_MANIFEST_ORDER_SCIENCE 50
#define DEPT_MANIFEST_ORDER_CARGO 60
#define DEPT_MANIFEST_ORDER_SERVICE 70
#define DEPT_MANIFEST_ORDER_CIVILIAN 80
#define DEPT_MANIFEST_ORDER_SILICON 90
#define DEPT_MANIFEST_ORDER_UNASSIGNED 666 // dummy department for people with no department


// used for /mob/dead/new_player/authenticated/proc/LateChoices()
#define DEPT_PREF_ORDER_COMMAND 	10
#define DEPT_PREF_ORDER_SECURITY 	20
#define DEPT_PREF_ORDER_ENGINEERING 30
#define DEPT_PREF_ORDER_MEDICAL 	40
#define DEPT_PREF_ORDER_SCIENCE 	50
#define DEPT_PREF_ORDER_CARGO 		60
#define DEPT_PREF_ORDER_SERVICE 	70
#define DEPT_PREF_ORDER_CIVILIAN 	80
#define DEPT_PREF_ORDER_SILICON 	90
