
#define COMPLETION_PRIORITY_BEFORE_INITIALISE 0

#define COMPLETION_PRIORITY_INITIALISE 50

#define COMPLETION_PRIORITY_ACTION_LOAD 100
#define COMPLETION_PRIORITY_LINKUP 101
#define COMPLETION_PRIORITY_PREVIEW 105
