//flags
#define IGNORE_NOSLOW	(1 << 0)

//conflict types

#define MOVE_CONFLICT_JETPACK "JETPACK"

//ids
#define MOVESPEED_ID_SANITY "sanity_component"

#define MOVESPEED_ID_MOB_GRAB_STATE "mob_grab_state"
#define MOVESPEED_ID_MOB_WALK_RUN "mob_walk_run"


//CONVERT BELOW

#define MOVESPEED_ID_SLIME_SEPIA "SLIME_SEPIA" // slime transforming sepia crossbreed


#define MOVESPEED_ID_BASIC_MOB_VARSPEED					"BASIC_MOB_VARSPEED_MODIFIER"


#define MOVESPEED_ID_NO_POWERCELL												"NO POWERCELL"

#define MOVESPEED_ID_SLOW_ARMOR							"SLOW_ARMOR "
#define MOVESPEED_ID_SLOW_SUITBOX						"SLOW_SUITBOX"

#define MOVESPEED_ID_INTERDICTION						"interdiction"

#define MOVESPEED_ID_NECRO_VIRUS_SLOWDOWN				"NECRO_VIRUS"
#define MOVESPEED_ID_GRUB_VIRUS_SLOWDOWN				"GRUB_VIRUS"
#define MOVESPEED_ID_LIGHT_VIRUS_SLOWDOWN				"LIGHT_VIRUS"

#define MOVESPEED_ID_SWIMMING							"SWIMMING_SPEED_MOD"

#define MOVESPEED_ID_DRAGON_RAGE						"DRAGON_RAGE"

#define MOVESPEED_ID_SMOKE								"SMOKE"

#define MOVESPEED_ID_HOLOPARA_FRENZY					"HOLOPARA_FRENZY"
