//Originally coded by ISaidNo, later modified by Kelenius. Ported from Baystation12.

/obj/structure/closet/crate/secure/loot
	name = "abandoned crate"
	desc = "What could be inside?"
	icon_state = "securecrate"
	integrity_failure = 0 //no breaking open the crate
	var/code = null
	var/lastattempt = null
	var/attempts = 10
	var/codelen = 4
	tamperproof = 90

/obj/structure/closet/crate/secure/loot/Initialize()
	. = ..()
	var/list/digits = list("1", "2", "3", "4", "5", "6", "7", "8", "9", "0")
	code = ""
	for(var/i = 0, i < codelen, i++)
		var/dig = pick(digits)
		code += dig
		digits -= dig  //there are never matching digits in the answer

	var/loot = rand(1,150) //150 different crates with varying chances of spawning
	switch(loot)
		if(1 to 5) //5% chance
			new /obj/item/reagent_containers/food/drinks/bottle/rum(src)
			new /obj/item/reagent_containers/food/snacks/grown/ambrosia/deus(src)
			new /obj/item/reagent_containers/food/drinks/bottle/whiskey(src)
			new /obj/item/lighter(src)
		if(6 to 10)
			new /obj/item/bedsheet(src)
			new /obj/item/kitchen/knife(src)
			new /obj/item/wirecutters(src)
			new /obj/item/screwdriver(src)
			new /obj/item/weldingtool(src)
			new /obj/item/hatchet(src)
			new /obj/item/crowbar(src)
		if(11 to 15)
			new /obj/item/reagent_containers/glass/beaker/bluespace(src)
		if(16 to 20)
			new /obj/item/stack/ore/diamond(src, 10)
		if(21 to 25)
			for(var/i in 1 to 5)
				new /obj/item/poster/random_contraband(src)
		if(26 to 30)
			for(var/i in 1 to 3)
				new /obj/item/reagent_containers/glass/beaker/noreact(src)
		if(31 to 35)
			new /obj/item/seeds/firelemon(src)
		if(36 to 40)
			new /obj/item/melee/baton(src)
		if(41 to 45)
			new /obj/item/clothing/under/shorts/red(src)
			new /obj/item/clothing/under/shorts/blue(src)
		if(46 to 50)
			new /obj/item/clothing/under/chameleon(src)
			for(var/i in 1 to 7)
				new /obj/item/clothing/neck/tie/horrible(src)
		if(51 to 52) // 2% chance
			new /obj/item/melee/classic_baton/police(src)
		if(53 to 54)
			new /obj/item/toy/balloon(src)
		if(55 to 56)
			var/newitem = pick(subtypesof(/obj/item/toy/prize))
			new newitem(src)
		if(57 to 58)
			new /obj/item/toy/syndicateballoon(src)
		if(59 to 60)
			new /obj/item/borg/upgrade/modkit/aoe/mobs(src)
			new /obj/item/clothing/suit/space(src)
			new /obj/item/clothing/head/helmet/space(src)
		if(61 to 62)
			for(var/i in 1 to 5)
				new /obj/item/clothing/head/kitty(src)
				new /obj/item/clothing/neck/petcollar(src)
		if(63 to 64)
			for(var/i in 1 to rand(4, 7))
				var/newcoin = pick(/obj/item/coin/silver, /obj/item/coin/silver, /obj/item/coin/silver, /obj/item/coin/iron, /obj/item/coin/iron, /obj/item/coin/iron, /obj/item/coin/gold, /obj/item/coin/diamond, /obj/item/coin/plasma, /obj/item/coin/uranium)
				new newcoin(src)
		if(65 to 66)
			new /obj/item/clothing/suit/ianshirt(src)
			new /obj/item/clothing/suit/hooded/ian_costume(src)
		if(67 to 68)
			for(var/i in 1 to rand(4, 7))
				var/newitem = pick(subtypesof(/obj/item/stock_parts) - /obj/item/stock_parts/subspace)
				new newitem(src)
		if(69 to 70)
			new /obj/item/stack/ore/bluespace_crystal(src, 5)
		if(71 to 72)
			new /obj/item/pickaxe/drill(src)
		if(73 to 74)
			new /obj/item/pickaxe/drill/jackhammer(src)
		if(75 to 76)
			new /obj/item/pickaxe/diamond(src)
		if(77 to 78)
			new /obj/item/pickaxe/drill/diamonddrill(src)
		if(79 to 80)
			new /obj/item/cane(src)
			new /obj/item/clothing/head/collectable/tophat(src)
		if(81 to 82)
			new /obj/item/gun/energy/plasmacutter(src)
		if(83 to 84)
			new /obj/item/toy/katana(src)
		if(85 to 86)
			new /obj/item/defibrillator/compact(src)
		if(87) //1% chance
			new /obj/item/weed_extract(src)
		if(88)
			new /obj/item/organ/brain(src)
		if(89)
			new /obj/item/organ/brain/alien(src)
		if(90)
			new /obj/item/organ/heart(src)
		if(91)
			new /obj/item/soulstone/anybody(src)
		if(92)
			new /obj/item/katana(src)
		if(93)
			new /obj/item/dnainjector/xraymut(src)
		if(94)
			new /obj/item/storage/backpack/clown(src)
			new /obj/item/clothing/under/rank/civilian/clown(src)
			new /obj/item/clothing/shoes/clown_shoes(src)
			new /obj/item/pda/clown(src)
			new /obj/item/clothing/mask/gas/clown_hat(src)
			new /obj/item/bikehorn(src)
			new /obj/item/toy/crayon/rainbow(src)
			new /obj/item/reagent_containers/spray/waterflower(src)
		if(95)
			new /obj/item/clothing/under/rank/civilian/mime(src)
			new /obj/item/clothing/shoes/sneakers/black(src)
			new /obj/item/pda/mime(src)
			new /obj/item/clothing/gloves/color/white(src)
			new /obj/item/clothing/mask/gas/mime(src)
			new /obj/item/clothing/head/beret(src)
			new /obj/item/clothing/suit/suspenders(src)
			new /obj/item/toy/crayon/mime(src)
			new /obj/item/reagent_containers/food/drinks/bottle/bottleofnothing(src)
		if(96)
			new /obj/item/hand_tele(src)
		if(97)
			new /obj/item/clothing/mask/balaclava
			new /obj/item/gun/ballistic/automatic/pistol(src)
			new /obj/item/ammo_box/magazine/m10mm(src)
		if(98)
			new /obj/item/katana/cursed(src)
		if(99)
			new /obj/item/storage/belt/champion(src)
			new /obj/item/clothing/mask/luchador(src)
		if(100)
			new /obj/item/clothing/head/bearpelt(src)
		if(101 to 105)
			var/ctype = pick(subtypesof(/datum/supply_pack))
			var/datum/supply_pack/pack = new ctype()
			for(var/item in pack.contains)
				new item(src)
			qdel(pack)
		if(106)
			new /obj/item/reagent_containers/glass/bottle/mannitol(src)
			new /obj/item/storage/pill_bottle/neurine(src)
			new /obj/item/organ/brain(src)
		if(107)
			new /obj/item/reagent_containers/glass/bottle/brainrot(src)
			new /obj/item/reagent_containers/glass/bottle/fake_gbs(src)
			new /obj/item/reagent_containers/glass/bottle/cold(src)
			new /obj/item/reagent_containers/glass/bottle/random_virus(src)
			new /obj/item/clothing/head/bio_hood/virology(src)
			new /obj/item/clothing/suit/bio_suit/virology(src)
			new /obj/item/tank/internals/oxygen/yellow(src)
			new /obj/item/clothing/gloves/color/latex/nitrile(src)
		if(108)
			new /obj/item/circuitboard/machine/protolathe(src)
		if(109)
			var/list/circuits = subtypesof(/obj/item/circuitboard)
			var/chosen_circuit = pick(circuits)
			new chosen_circuit(src)
		if(110)
			new /obj/item/clothing/head/bronze(src)
			new /obj/item/clothing/shoes/bronze(src)
			new /obj/item/clothing/suit/bronze(src)
			new /obj/item/stack/tile/bronze/thirty(src)
		if(111)
			new /obj/item/clothing/accessory/medal/bronze_heart(src)
			new /obj/item/clothing/accessory/medal/conduct(src)
			new /obj/item/clothing/accessory/medal/plasma(src)
			new /obj/item/clothing/accessory/medal/plasma/nobel_science(src)
			new /obj/item/clothing/accessory/medal/ribbon/cargo(src)
			new /obj/item/clothing/accessory/medal/silver/excellence(src)
			new /obj/item/clothing/accessory/medal/silver/security(src)
			new /obj/item/clothing/accessory/medal/silver/valor(src)
		if(112)
			new /obj/item/clothing/accessory/medal/gold/heroism(src)
			new /obj/item/clothing/accessory/medal/gold/captain(src)
			new /obj/item/reagent_containers/food/drinks/trophy/gold_cup(src)
			new /obj/item/reagent_containers/food/snacks/grown/apple/gold(src)
		if(113)//Lite, mid and heavy are Snowndin lootdrops. Putting a spawner into the chest result things spawn on top of it instead of inside.
			switch(pickweight(list("heavystuff1", "heavystuff2", "heavystuff3", "heavystuff4", "heavystuff5", "heavystuff6", "heavystuff7", "heavystuff8")))
				if("heavystuff1")
					new /obj/item/banhammer(src)
					new /obj/item/clothing/head/helmet/riot(src)
					new /obj/item/banhammer(src)
					new /obj/item/clothing/head/helmet/riot(src)
					new /obj/item/banhammer(src)
					new /obj/item/clothing/head/helmet/riot(src)
					new /obj/item/banhammer(src)
					new /obj/item/clothing/head/helmet/riot(src)
					new /obj/item/banhammer(src)
					new /obj/item/clothing/head/helmet/riot(src)
				if("heavystuff2")
					new /obj/item/clothing/head/helmet/roman/legionnaire(src)
					new /obj/item/clothing/shoes/roman(src)
					new /obj/item/clothing/under/costume/roman(src)
					new /obj/item/shield/riot/roman(src)
					new /obj/item/melee/shank(src)
				if("heavystuff3")
					new /obj/item/twohanded/fireaxe(src)
					new /obj/item/organ/brain/alien(src)
				if("heavystuff4")
					new /obj/item/modular_computer/tablet/preset/advanced(src)
				if("heavystuff5")
					new /obj/item/stack/spacecash/c1000(src)
					new /obj/item/stack/spacecash/c1000(src)
					new /obj/item/clothing/head/collectable/tophat(src)
					new /obj/item/storage/fancy/cigarettes/cigars/cohiba(src)
				if("heavystuff6")
					new /obj/item/borg/upgrade/syndicate(src)
				if("heavystuff7")
					new /obj/item/borg/upgrade/selfrepair(src)
				if("heavystuff8")
					new /obj/item/clothing/suit/armor/riot/knight/red(src)
					new /obj/item/clothing/gloves/plate/red(src)
					new /obj/item/clothing/shoes/plate/red(src)
					new /obj/item/clothing/head/helmet/knight/red(src)
					new /obj/item/kitchen/knife/butcher(src)
		if(114)
			for(var/food in 5)
				food = pick(subtypesof(/obj/item/reagent_containers/food/snacks))
				new food(src)
		if(115)
			new /obj/item/kitchen/knife/rainbowknife(src)//Yooo my 400000$ knife lets sell it and become rich!!!!11
		if(116)
			switch(pickweight(list("litestuff", "litestuff2", "litestuff3", "litestuff4", "litestuff5")))
				if("litestuff")
					new /obj/item/melee/classic_baton/police(src)
					new /obj/item/storage/firstaid/regular(src)
					new /obj/item/storage/toolbox/syndicate(src)
				if("litestuff2")
					new /obj/item/melee/classic_baton/police/telescopic(src)
					new /obj/item/storage/firstaid/toxin(src)
					new /obj/item/grenade/clusterbuster/smoke(src)
					new /obj/item/clothing/shoes/chameleon/noslip(src)
				if("litestuff3")
					new /obj/item/clothing/under/chameleon(src)
					new /obj/item/clothing/neck/necklace/dope(src)
					new /obj/item/clothing/mask/chameleon(src)
				if("litestuff4")
					new /obj/item/storage/firstaid/regular(src)
					new /obj/item/storage/firstaid/toxin(src)
					new /obj/item/storage/firstaid/brute(src)
					new /obj/item/storage/firstaid/fire(src)
					new /obj/item/borg/upgrade/ddrill(src)
					new /obj/item/borg/upgrade/soh(src)
				if("litestuff5")
					new /obj/item/grenade/clusterbuster/smoke(src)
		if(117 to 120)
			new /obj/item/tank/jetpack/void(src)
			new /obj/item/clothing/mask/breath(src)
			new /obj/item/clothing/head/helmet/space/nasavoid(src)
			new /obj/item/clothing/suit/space/nasavoid(src)
			new /obj/item/crowbar(src)
			new /obj/item/stock_parts/cell(src)
			new /obj/item/multitool(src)
		if(121)
			new /obj/item/clothing/gloves/chameleon/combat(src)
			for(var/gloves in 6)
				gloves = pick(subtypesof(/obj/item/clothing/gloves/color))
				new gloves(src)
		if(122)
			new /obj/item/storage/box/syndie_kit/chameleon(src)
		if(123)
			for(var/pizza in 5)
				pizza = pick(subtypesof(/obj/item/pizzabox))
				new pizza(src)
		if(124)
			new /obj/item/clothing/shoes/chameleon/noslip(src)
			new /obj/item/reagent_containers/spray/waterflower(src)
		if(125)
			new /obj/item/clothing/shoes/clown_shoes/combat(src)
			new /obj/item/storage/backpack/duffelbag/clown/syndie(src)
			new /obj/item/pda/clown(src)
			new /obj/item/megaphone/clown(src)
			new /obj/item/clothing/mask/gas/clown_hat(src)
		if(126)
			new /obj/item/reagent_containers/spray/chemsprayer/janitor/clown(src)
		if(127)
			new /obj/item/clothing/head/crown/fancy(src)           //monke king
			new /obj/item/storage/box/monkeycubes(src)
			new /obj/item/storage/box/monkeycubes(src)
			new /obj/item/storage/box/monkeycubes(src)
		if(128)
			switch(pickweight(list("midstuff1", "midstuff2", "midstuff3", "midstuff4", "midstuff5", "midstuff6", "midstuff7", "midstuff8", "midstuff9")))
				if("midstuff1")
					new /obj/item/shield/riot/tele(src)
					new /obj/item/pickaxe/drill/diamonddrill(src)
				if("midstuff2")
					new /obj/item/shield/riot/buckler(src)
					new /obj/item/melee/baseball_bat(src)
				if("midstuff3")
					new /obj/item/dnainjector/geladikinesis(src)
				if("midstuff4")
					new /obj/item/storage/backpack/duffelbag/syndie(src)
					new /obj/item/lipstick(src)
					new /obj/item/flashlight/glowstick/red(src)
				if("midstuff5")
					new /obj/item/stack/sheet/mineral/diamond{amount = 15}(src)
					new /obj/item/stack/sheet/mineral/uranium{amount = 15}(src)
					new /obj/item/stack/sheet/mineral/plasma{amount = 15}(src)
					new /obj/item/stack/sheet/mineral/gold{amount = 15}(src)
				if("midstuff6")
					new /obj/item/book/granter/crafting_recipe/cooking_sweets_101(src)
				if("midstuff7")
					new /obj/item/borg/upgrade/vtec(src)
					new /obj/item/borg/upgrade/disablercooler(src)
				if("midstuff8")
					new /obj/item/book/granter/spell/knock(src)
				if("midstuff9")
					new /obj/item/book/granter/crafting_recipe(src)
					new /obj/item/book/granter/spell/smoke/lesser(src)
		if(129)
			new /obj/item/stack/sheet/mineral/snow{amount = 25}(src)
			new /obj/item/toy/snowball(src)
			new /obj/item/twohanded/spear(src)
		if(130)
			new /mob/living/simple_animal/bot/medbot(src)
			new /mob/living/simple_animal/bot/floorbot(src)
			new /mob/living/simple_animal/bot/cleanbot(src)
		if(131)
			new /obj/item/card/emagfake(src)
			new /obj/item/ammo_box/magazine/toy/pistol/riot(src)
			new /obj/item/gun/ballistic/automatic/toy/pistol/riot(src)
			new /obj/item/toy/sword(src)
			new /obj/item/toy/cards/deck/syndicate(src)
			new /obj/item/toy/syndicateballoon(src)
			new /obj/item/bedsheet/syndie(src)
			new /obj/item/toy/plush/nukeplushie(src)
			new /obj/item/toy/nuke(src)
			new /obj/item/disk/nuclear/fake(src)
		if(132)
			new /obj/item/pneumatic_cannon(src)
		if(133)
			new /obj/item/dnainjector/elvismut(src)
			new /obj/item/dnainjector/firemut(src)
			new /obj/item/dnainjector/glow(src)
			new /obj/item/dnainjector/spastic(src)
			new /obj/item/dnainjector/epimut(src)
			new /obj/item/handmirror(src)
			new /obj/item/razor(src)
		if(134 to 138)
			for(var/stick in 7)
				stick = pick(subtypesof(/obj/item/flashlight/glowstick))
				new stick(src)
		if(139 to 141)
			new /obj/effect/spawner/lootdrop/two_percent_xeno_egg_spawner(src)//Two percent for a crate to spawn a two percent xeno spawner.
			new /obj/item/clothing/suit/xenos(src)                            //This means it's about one percent or less to get a xeno egg from an abandoned crate, I don't know.
			new /obj/item/toy/toy_xeno(src)                                   //I actually don't give a shit how much percent it has.
			new /obj/item/clothing/head/xenos(src)                            //I'm not memorizing the multiplication table. I don't have a calculator and my ass is fat.
		if(142 to 146)
			new /mob/living/simple_animal/cluwne(src)
			new /mob/living/simple_animal/cluwne(src)
			new /mob/living/simple_animal/cluwne(src)
			new /mob/living/simple_animal/cluwne(src)
			new /obj/item/dnainjector/clumsymut(src)
			new /obj/item/dnainjector/cluwnemut(src)
		if(147)
			new /obj/item/clothing/head/helmet/swat/nanotrasen(src)
			new /obj/item/clothing/under/rank/security/officer(src)
			new /obj/item/clothing/suit/armor/vest(src)
			new /obj/item/clothing/shoes/combat/swat(src)
			new /obj/item/clothing/gloves/combat(src)
		if(148)
			for(var/ears in 4)
				ears = pick(subtypesof(/obj/item/organ/ears))
				new ears
		if(149)
			for(var/soda in 8)
				soda = pick(subtypesof(/obj/item/reagent_containers/food/drinks/soda_cans))
				new soda(src)
		if(150)
			new /obj/item/bedsheet/centcom(src)
			new /obj/item/clothing/under/rank/centcom/commander(src)
			new /obj/item/clothing/head/centhat(src)
			new /obj/effect/decal/remains/human(src)
			new /obj/item/gun/energy/e_gun(src)
			new /obj/item/paper/fluff/awaymissions/centcom/gateway_memo(src)

//ATTACK HAND IGNORING PARENT RETURN VALUE
/obj/structure/closet/crate/secure/loot/attack_hand(mob/user)
	if(locked)
		to_chat(user, "<span class='notice'>The crate is locked with a Deca-code lock.</span>")
		var/input = capped_input(usr, "Enter [codelen] digits. All digits must be unique.", "Deca-Code Lock")
		if(user.canUseTopic(src, BE_CLOSE))
			var/list/sanitised = list()
			var/sanitycheck = TRUE
			var/char = ""
			var/length_input = length(input)
			for(var/i = 1, i <= length_input, i += length(char)) //put the guess into a list
				char = input[i]
				sanitised += text2num(char)
			for(var/i = 1, i <= length(sanitised) - 1, i++) //compare each digit in the guess to all those following it
				for(var/j = i + 1, j <= length(sanitised), j++)
					if(sanitised[i] == sanitised[j])
						sanitycheck = FALSE //if a digit is repeated, reject the input
			if(input == code)
				to_chat(user, "<span class='notice'>The crate unlocks!</span>")
				locked = FALSE
				cut_overlays()
				add_overlay("securecrateg")
				add_overlay("[icon_state]_door") //needs to put the door overlayer back cause of this snowflake code
				tamperproof = 0 // set explosion chance to zero, so we dont accidently hit it with a multitool and instantly die
			else if(!input || !sanitycheck || length(sanitised) != codelen)
				to_chat(user, "<span class='notice'>You leave the crate alone.</span>")
			else
				to_chat(user, "<span class='warning'>A red light flashes.</span>")
				lastattempt = input
				attempts--
				if(attempts == 0)
					boom(user)
	else
		return ..()

/obj/structure/closet/crate/secure/loot/AltClick(mob/living/user)
	if(!user.canUseTopic(src, BE_CLOSE))
		return
	return attack_hand(user) //this helps you not blow up so easily by overriding unlocking which results in an immediate boom.

/obj/structure/closet/crate/secure/loot/attackby(obj/item/W, mob/user)
	if(locked)
		if(W.tool_behaviour == TOOL_MULTITOOL)
			to_chat(user, "<span class='notice'>DECA-CODE LOCK REPORT:</span>")
			if(attempts == 1)
				to_chat(user, "<span class='warning'>* Anti-Tamper Bomb will activate on next failed access attempt.</span>")
			else
				to_chat(user, "<span class='notice'>* Anti-Tamper Bomb will activate after [attempts] failed access attempts.</span>")
			if(lastattempt != null)
				var/bulls = 0 //right position, right number
				var/cows = 0 //wrong position but in the puzzle

				var/lastattempt_char = ""
				var/length_lastattempt = length(lastattempt)
				var/lastattempt_it = 1

				var/code_char = ""
				var/length_code = length(code)
				var/code_it = 1

				while(lastattempt_it <= length_lastattempt && code_it <= length_code) // Go through list and count matches
					lastattempt_char = lastattempt[lastattempt_it]
					code_char = code[code_it]
					if(lastattempt_char == code_char)
						++bulls
					else if(findtext(code, lastattempt_char))
						++cows

					lastattempt_it += length(lastattempt_char)
					code_it += length(code_char)

				to_chat(user, "<span class='notice'>Last code attempt, [lastattempt], had [bulls] correct digits at correct positions and [cows] correct digits at incorrect positions.</span>")
			return
	return ..()

/obj/structure/closet/secure/loot/dive_into(mob/living/user)
	if(!locked)
		return ..()
	to_chat(user, "<span class='notice'>That seems like a stupid idea.</span>")
	return FALSE

/obj/structure/closet/crate/secure/loot/emag_act(mob/user)
	if(locked)
		boom(user)

/obj/structure/closet/crate/secure/loot/togglelock(mob/user)
	if(locked)
		boom(user)
	else
		..()

/obj/structure/closet/crate/secure/loot/deconstruct(disassembled = TRUE)
	boom()
