// UI states, which are mirrored from the BYOND code.
export const UI_INTERACTIVE = 2;
export const UI_UPDATE = 1;
export const UI_DISABLED = 0;
export const UI_CLOSE = -1;

// All game related colors are stored here
export const COLORS = {
  // Department colors
  department: {
    captain: '#c06616',
    security: '#e74c3c',
    medbay: '#3498db',
    science: '#9b59b6',
    engineering: '#f1c40f',
    cargo: '#f39c12',
    centcom: '#00c100',
    other: '#c38312',
  },
  // Damage type colors
  damageType: {
    oxy: '#3498db',
    toxin: '#2ecc71',
    burn: '#e67e22',
    brute: '#e74c3c',
  },
};

// Colors defined in CSS
export const CSS_COLORS = [
  'black',
  'white',
  'red',
  'orange',
  'yellow',
  'olive',
  'green',
  'teal',
  'blue',
  'violet',
  'purple',
  'pink',
  'brown',
  'grey',
  'good',
  'average',
  'bad',
  'label',
];

export const RADIO_CHANNELS = [
  {
    name: 'Syndicate',
    freq: 1213,
    color: '#a52a2a',
  },
  {
    name: 'Red Team',
    freq: 1215,
    color: '#ff4444',
  },
  {
    name: 'Blue Team',
    freq: 1217,
    color: '#3434fd',
  },
  {
    name: 'CentCom',
    freq: 1337,
    color: '#2681a5',
  },
  {
    name: 'Supply',
    freq: 1347,
    color: '#b88646',
  },
  {
    name: 'Service',
    freq: 1349,
    color: '#6ca729',
  },
  {
    name: 'Science',
    freq: 1351,
    color: '#c68cfa',
  },
  {
    name: 'Command',
    freq: 1353,
    color: '#5177ff',
  },
  {
    name: 'Medical',
    freq: 1355,
    color: '#57b8f0',
  },
  {
    name: 'Engineering',
    freq: 1357,
    color: '#f37746',
  },
  {
    name: 'Security',
    freq: 1359,
    color: '#dd3535',
  },
  {
    name: 'AI Private',
    freq: 1447,
    color: '#d65d95',
  },
  {
    name: 'Common',
    freq: 1459,
    color: '#1ecc43',
  },
];

const GASES = [
  {
    'id': 'o2',
    'name': 'Oxygen',
    'label': 'O₂',
    'color': 'blue',
  },
  {
    'id': 'n2',
    'name': 'Nitrogen',
    'label': 'N₂',
    'color': 'red',
  },
  {
    'id': 'co2',
    'name': 'Carbon Dioxide',
    'label': 'CO₂',
    'color': 'grey',
  },
  {
    'id': 'plasma',
    'name': 'Plasma',
    'label': 'Plasma',
    'color': 'pink',
  },
  {
    'id': 'water_vapor',
    'name': 'Water Vapor',
    'label': 'H₂O',
    'color': 'grey',
  },
  {
    'id': 'nob',
    'name': 'Hyper-noblium',
    'label': 'Hyper-nob',
    'color': 'teal',
  },
  {
    'id': 'n2o',
    'name': 'Nitrous Oxide',
    'label': 'N₂O',
    'color': 'red',
  },
  {
    'id': 'no2',
    'name': 'Nitryl',
    'label': 'NO₂',
    'color': 'brown',
  },
  {
    'id': 'tritium',
    'name': 'Tritium',
    'label': 'Tritium',
    'color': 'green',
  },
  {
    'id': 'bz',
    'name': 'BZ',
    'label': 'BZ',
    'color': 'purple',
  },
  {
    'id': 'stim',
    'name': 'Stimulum',
    'label': 'Stimulum',
    'color': 'purple',
  },
  {
    'id': 'pluox',
    'name': 'Pluoxium',
    'label': 'Pluoxium',
    'color': 'blue',
  },
  {
    'id': 'miasma',
    'name': 'Miasma',
    'label': 'Miasma',
    'color': 'olive',
  },
  // BEGIN
  {
    'id': 'ethanol',
    'name': 'ethanol',
    'label': 'ethanol',
    'color': 'olive',
  },
  {
    'id': 'beer',
    'name': 'beer',
    'label': 'beer',
    'color': 'olive',
  },
  {
    'id': 'ftliver',
    'name': 'ftliver',
    'label': 'ftliver',
    'color': 'olive',
  },
  {
    'id': 'light',
    'name': 'light',
    'label': 'light',
    'color': 'olive',
  },
  {
    'id': 'green',
    'name': 'green',
    'label': 'green',
    'color': 'olive',
  },
  {
    'id': 'kahlua',
    'name': 'kahlua',
    'label': 'kahlua',
    'color': 'olive',
  },
  {
    'id': 'whiskey',
    'name': 'whiskey',
    'label': 'whiskey',
    'color': 'olive',
  },
  {
    'id': 'thirteenloko',
    'name': 'thirteenloko',
    'label': 'thirteenloko',
    'color': 'olive',
  },
  {
    'id': 'vodka',
    'name': 'vodka',
    'label': 'vodka',
    'color': 'olive',
  },
  {
    'id': 'bilk',
    'name': 'bilk',
    'label': 'bilk',
    'color': 'olive',
  },
  {
    'id': 'threemileisland',
    'name': 'threemileisland',
    'label': 'threemileisland',
    'color': 'olive',
  },
  {
    'id': 'gin',
    'name': 'gin',
    'label': 'gin',
    'color': 'olive',
  },
  {
    'id': 'rum',
    'name': 'rum',
    'label': 'rum',
    'color': 'olive',
  },
  {
    'id': 'tequila',
    'name': 'tequila',
    'label': 'tequila',
    'color': 'olive',
  },
  {
    'id': 'vermouth',
    'name': 'vermouth',
    'label': 'vermouth',
    'color': 'olive',
  },
  {
    'id': 'wine',
    'name': 'wine',
    'label': 'wine',
    'color': 'olive',
  },
  {
    'id': 'lizardwine',
    'name': 'lizardwine',
    'label': 'lizardwine',
    'color': 'olive',
  },
  {
    'id': 'grappa',
    'name': 'grappa',
    'label': 'grappa',
    'color': 'olive',
  },
  {
    'id': 'cognac',
    'name': 'cognac',
    'label': 'cognac',
    'color': 'olive',
  },
  {
    'id': 'absinthe',
    'name': 'absinthe',
    'label': 'absinthe',
    'color': 'olive',
  },
  {
    'id': 'hooch',
    'name': 'hooch',
    'label': 'hooch',
    'color': 'olive',
  },
  {
    'id': 'ale',
    'name': 'ale',
    'label': 'ale',
    'color': 'olive',
  },
  {
    'id': 'goldschlager',
    'name': 'goldschlager',
    'label': 'goldschlager',
    'color': 'olive',
  },
  {
    'id': 'patron',
    'name': 'patron',
    'label': 'patron',
    'color': 'olive',
  },
  {
    'id': 'gintonic',
    'name': 'gintonic',
    'label': 'gintonic',
    'color': 'olive',
  },
  {
    'id': 'rum_coke',
    'name': 'rum_coke',
    'label': 'rum_coke',
    'color': 'olive',
  },
  {
    'id': 'cuba_libre',
    'name': 'cuba_libre',
    'label': 'cuba_libre',
    'color': 'olive',
  },
  {
    'id': 'whiskey_cola',
    'name': 'whiskey_cola',
    'label': 'whiskey_cola',
    'color': 'olive',
  },
  {
    'id': 'martini',
    'name': 'martini',
    'label': 'martini',
    'color': 'olive',
  },
  {
    'id': 'vodkamartini',
    'name': 'vodkamartini',
    'label': 'vodkamartini',
    'color': 'olive',
  },
  {
    'id': 'white_russian',
    'name': 'white_russian',
    'label': 'white_russian',
    'color': 'olive',
  },
  {
    'id': 'vodka_cola',
    'name': 'vodka_cola',
    'label': 'vodka_cola',
    'color': 'olive',
  },
  {
    'id': 'black_roulette',
    'name': 'black_roulette',
    'label': 'black_roulette',
    'color': 'olive',
  },
  {
    'id': 'triple_coke',
    'name': 'triple_coke',
    'label': 'triple_coke',
    'color': 'olive',
  },
  {
    'id': 'salty_water',
    'name': 'salty_water',
    'label': 'salty_water',
    'color': 'olive',
  },
  {
    'id': 'screwdrivercocktail',
    'name': 'screwdrivercocktail',
    'label': 'screwdrivercocktail',
    'color': 'olive',
  },
  {
    'id': 'booger',
    'name': 'booger',
    'label': 'booger',
    'color': 'olive',
  },
  {
    'id': 'bloody_mary',
    'name': 'bloody_mary',
    'label': 'bloody_mary',
    'color': 'olive',
  },
  {
    'id': 'brave_bull',
    'name': 'brave_bull',
    'label': 'brave_bull',
    'color': 'olive',
  },
  {
    'id': 'tequila_sunrise',
    'name': 'tequila_sunrise',
    'label': 'tequila_sunrise',
    'color': 'olive',
  },
  {
    'id': 'toxins_special',
    'name': 'toxins_special',
    'label': 'toxins_special',
    'color': 'olive',
  },
  {
    'id': 'beepsky_smash',
    'name': 'beepsky_smash',
    'label': 'beepsky_smash',
    'color': 'olive',
  },
  {
    'id': 'irish_cream',
    'name': 'irish_cream',
    'label': 'irish_cream',
    'color': 'olive',
  },
  {
    'id': 'manly_dorf',
    'name': 'manly_dorf',
    'label': 'manly_dorf',
    'color': 'olive',
  },
  {
    'id': 'longislandicedtea',
    'name': 'longislandicedtea',
    'label': 'longislandicedtea',
    'color': 'olive',
  },
  {
    'id': 'moonshine',
    'name': 'moonshine',
    'label': 'moonshine',
    'color': 'olive',
  },
  {
    'id': 'b52',
    'name': 'b52',
    'label': 'b52',
    'color': 'olive',
  },
  {
    'id': 'irishcoffee',
    'name': 'irishcoffee',
    'label': 'irishcoffee',
    'color': 'olive',
  },
  {
    'id': 'margarita',
    'name': 'margarita',
    'label': 'margarita',
    'color': 'olive',
  },
  {
    'id': 'black_russian',
    'name': 'black_russian',
    'label': 'black_russian',
    'color': 'olive',
  },
  {
    'id': 'manhattan',
    'name': 'manhattan',
    'label': 'manhattan',
    'color': 'olive',
  },
  {
    'id': 'manhattan_proj',
    'name': 'manhattan_proj',
    'label': 'manhattan_proj',
    'color': 'olive',
  },
  {
    'id': 'whiskeysoda',
    'name': 'whiskeysoda',
    'label': 'whiskeysoda',
    'color': 'olive',
  },
  {
    'id': 'antifreeze',
    'name': 'antifreeze',
    'label': 'antifreeze',
    'color': 'olive',
  },
  {
    'id': 'barefoot',
    'name': 'barefoot',
    'label': 'barefoot',
    'color': 'olive',
  },
  {
    'id': 'snowwhite',
    'name': 'snowwhite',
    'label': 'snowwhite',
    'color': 'olive',
  },
  {
    'id': 'demonsblood',
    'name': 'demonsblood',
    'label': 'demonsblood',
    'color': 'olive',
  },
  {
    'id': 'devilskiss',
    'name': 'devilskiss',
    'label': 'devilskiss',
    'color': 'olive',
  },
  {
    'id': 'vodkatonic',
    'name': 'vodkatonic',
    'label': 'vodkatonic',
    'color': 'olive',
  },
  {
    'id': 'ginfizz',
    'name': 'ginfizz',
    'label': 'ginfizz',
    'color': 'olive',
  },
  {
    'id': 'bahama_mama',
    'name': 'bahama_mama',
    'label': 'bahama_mama',
    'color': 'olive',
  },
  {
    'id': 'singulo',
    'name': 'singulo',
    'label': 'singulo',
    'color': 'olive',
  },
  {
    'id': 'sbiten',
    'name': 'sbiten',
    'label': 'sbiten',
    'color': 'olive',
  },
  {
    'id': 'red_mead',
    'name': 'red_mead',
    'label': 'red_mead',
    'color': 'olive',
  },
  {
    'id': 'mead',
    'name': 'mead',
    'label': 'mead',
    'color': 'olive',
  },
  {
    'id': 'iced_beer',
    'name': 'iced_beer',
    'label': 'iced_beer',
    'color': 'olive',
  },
  {
    'id': 'grog',
    'name': 'grog',
    'label': 'grog',
    'color': 'olive',
  },
  {
    'id': 'aloe',
    'name': 'aloe',
    'label': 'aloe',
    'color': 'olive',
  },
  {
    'id': 'andalusia',
    'name': 'andalusia',
    'label': 'andalusia',
    'color': 'olive',
  },
  {
    'id': 'alliescocktail',
    'name': 'alliescocktail',
    'label': 'alliescocktail',
    'color': 'olive',
  },
  {
    'id': 'acid_spit',
    'name': 'acid_spit',
    'label': 'acid_spit',
    'color': 'olive',
  },
  {
    'id': 'amasec',
    'name': 'amasec',
    'label': 'amasec',
    'color': 'olive',
  },
  {
    'id': 'changelingsting',
    'name': 'changelingsting',
    'label': 'changelingsting',
    'color': 'olive',
  },
  {
    'id': 'irishcarbomb',
    'name': 'irishcarbomb',
    'label': 'irishcarbomb',
    'color': 'olive',
  },
  {
    'id': 'syndicatebomb',
    'name': 'syndicatebomb',
    'label': 'syndicatebomb',
    'color': 'olive',
  },
  {
    'id': 'erikasurprise',
    'name': 'erikasurprise',
    'label': 'erikasurprise',
    'color': 'olive',
  },
  {
    'id': 'driestmartini',
    'name': 'driestmartini',
    'label': 'driestmartini',
    'color': 'olive',
  },
  {
    'id': 'bananahonk',
    'name': 'bananahonk',
    'label': 'bananahonk',
    'color': 'olive',
  },
  {
    'id': 'silencer',
    'name': 'silencer',
    'label': 'silencer',
    'color': 'olive',
  },
  {
    'id': 'drunkenblumpkin',
    'name': 'drunkenblumpkin',
    'label': 'drunkenblumpkin',
    'color': 'olive',
  },
  {
    'id': 'whiskey_sour',
    'name': 'whiskey_sour',
    'label': 'whiskey_sour',
    'color': 'olive',
  },
  {
    'id': 'hcider',
    'name': 'hcider',
    'label': 'hcider',
    'color': 'olive',
  },
  {
    'id': 'fetching_fizz',
    'name': 'fetching_fizz',
    'label': 'fetching_fizz',
    'color': 'olive',
  },
  {
    'id': 'hearty_punch',
    'name': 'hearty_punch',
    'label': 'hearty_punch',
    'color': 'olive',
  },
  {
    'id': 'bacchus_blessing',
    'name': 'bacchus_blessing',
    'label': 'bacchus_blessing',
    'color': 'olive',
  },
  {
    'id': 'atomicbomb',
    'name': 'atomicbomb',
    'label': 'atomicbomb',
    'color': 'olive',
  },
  {
    'id': 'gargle_blaster',
    'name': 'gargle_blaster',
    'label': 'gargle_blaster',
    'color': 'olive',
  },
  {
    'id': 'neurotoxin',
    'name': 'neurotoxin',
    'label': 'neurotoxin',
    'color': 'olive',
  },
  {
    'id': 'hippies_delight',
    'name': 'hippies_delight',
    'label': 'hippies_delight',
    'color': 'olive',
  },
  {
    'id': 'eggnog',
    'name': 'eggnog',
    'label': 'eggnog',
    'color': 'olive',
  },
  {
    'id': 'narsour',
    'name': 'narsour',
    'label': 'narsour',
    'color': 'olive',
  },
  {
    'id': 'triple_sec',
    'name': 'triple_sec',
    'label': 'triple_sec',
    'color': 'olive',
  },
  {
    'id': 'creme_de_menthe',
    'name': 'creme_de_menthe',
    'label': 'creme_de_menthe',
    'color': 'olive',
  },
  {
    'id': 'creme_de_cacao',
    'name': 'creme_de_cacao',
    'label': 'creme_de_cacao',
    'color': 'olive',
  },
  {
    'id': 'quadruple_sec',
    'name': 'quadruple_sec',
    'label': 'quadruple_sec',
    'color': 'olive',
  },
  {
    'id': 'quintuple_sec',
    'name': 'quintuple_sec',
    'label': 'quintuple_sec',
    'color': 'olive',
  },
  {
    'id': 'grasshopper',
    'name': 'grasshopper',
    'label': 'grasshopper',
    'color': 'olive',
  },
  {
    'id': 'stinger',
    'name': 'stinger',
    'label': 'stinger',
    'color': 'olive',
  },
  {
    'id': 'bastion_bourbon',
    'name': 'bastion_bourbon',
    'label': 'bastion_bourbon',
    'color': 'olive',
  },
  {
    'id': 'squirt_cider',
    'name': 'squirt_cider',
    'label': 'squirt_cider',
    'color': 'olive',
  },
  {
    'id': 'fringe_weaver',
    'name': 'fringe_weaver',
    'label': 'fringe_weaver',
    'color': 'olive',
  },
  {
    'id': 'sugar_rush',
    'name': 'sugar_rush',
    'label': 'sugar_rush',
    'color': 'olive',
  },
  {
    'id': 'crevice_spike',
    'name': 'crevice_spike',
    'label': 'crevice_spike',
    'color': 'olive',
  },
  {
    'id': 'sake',
    'name': 'sake',
    'label': 'sake',
    'color': 'olive',
  },
  {
    'id': 'peppermint_patty',
    'name': 'peppermint_patty',
    'label': 'peppermint_patty',
    'color': 'olive',
  },
  {
    'id': 'alexander',
    'name': 'alexander',
    'label': 'alexander',
    'color': 'olive',
  },
  {
    'id': 'sidecar',
    'name': 'sidecar',
    'label': 'sidecar',
    'color': 'olive',
  },
  {
    'id': 'between_the_sheets',
    'name': 'between_the_sheets',
    'label': 'between_the_sheets',
    'color': 'olive',
  },
  {
    'id': 'kamikaze',
    'name': 'kamikaze',
    'label': 'kamikaze',
    'color': 'olive',
  },
  {
    'id': 'mojito',
    'name': 'mojito',
    'label': 'mojito',
    'color': 'olive',
  },
  {
    'id': 'fernet',
    'name': 'fernet',
    'label': 'fernet',
    'color': 'olive',
  },
  {
    'id': 'fernet_cola',
    'name': 'fernet_cola',
    'label': 'fernet_cola',
    'color': 'olive',
  },
  {
    'id': 'fanciulli',
    'name': 'fanciulli',
    'label': 'fanciulli',
    'color': 'olive',
  },
  {
    'id': 'branca_menta',
    'name': 'branca_menta',
    'label': 'branca_menta',
    'color': 'olive',
  },
  {
    'id': 'blank_paper',
    'name': 'blank_paper',
    'label': 'blank_paper',
    'color': 'olive',
  },
  {
    'id': 'fruit_wine',
    'name': 'fruit_wine',
    'label': 'fruit_wine',
    'color': 'olive',
  },
  {
    'id': 'champagne',
    'name': 'champagne',
    'label': 'champagne',
    'color': 'olive',
  },
  {
    'id': 'wizz_fizz',
    'name': 'wizz_fizz',
    'label': 'wizz_fizz',
    'color': 'olive',
  },
  {
    'id': 'bug_spray',
    'name': 'bug_spray',
    'label': 'bug_spray',
    'color': 'olive',
  },
  {
    'id': 'applejack',
    'name': 'applejack',
    'label': 'applejack',
    'color': 'olive',
  },
  {
    'id': 'jack_rose',
    'name': 'jack_rose',
    'label': 'jack_rose',
    'color': 'olive',
  },
  {
    'id': 'turbo',
    'name': 'turbo',
    'label': 'turbo',
    'color': 'olive',
  },
  {
    'id': 'old_timer',
    'name': 'old_timer',
    'label': 'old_timer',
    'color': 'olive',
  },
  {
    'id': 'rubberneck',
    'name': 'rubberneck',
    'label': 'rubberneck',
    'color': 'olive',
  },
  {
    'id': 'duplex',
    'name': 'duplex',
    'label': 'duplex',
    'color': 'olive',
  },
  {
    'id': 'trappist',
    'name': 'trappist',
    'label': 'trappist',
    'color': 'olive',
  },
  {
    'id': 'blazaam',
    'name': 'blazaam',
    'label': 'blazaam',
    'color': 'olive',
  },
  {
    'id': 'planet_cracker',
    'name': 'planet_cracker',
    'label': 'planet_cracker',
    'color': 'olive',
  },
  {
    'id': 'mauna_loa',
    'name': 'mauna_loa',
    'label': 'mauna_loa',
    'color': 'olive',
  },
  {
    'id': 'plasmaflood',
    'name': 'plasmaflood',
    'label': 'plasmaflood',
    'color': 'olive',
  },
  {
    'id': 'fourthwall',
    'name': 'fourthwall',
    'label': 'fourthwall',
    'color': 'olive',
  },
  {
    'id': 'ratvander',
    'name': 'ratvander',
    'label': 'ratvander',
    'color': 'olive',
  },
  {
    'id': 'icewing',
    'name': 'icewing',
    'label': 'icewing',
    'color': 'olive',
  },
  {
    'id': 'sarsaparilliansunset',
    'name': 'sarsaparilliansunset',
    'label': 'sarsaparilliansunset',
    'color': 'olive',
  },
  {
    'id': 'beesknees',
    'name': 'beesknees',
    'label': 'beesknees',
    'color': 'olive',
  },
  {
    'id': 'orangejuice',
    'name': 'orangejuice',
    'label': 'orangejuice',
    'color': 'olive',
  },
  {
    'id': 'tomatojuice',
    'name': 'tomatojuice',
    'label': 'tomatojuice',
    'color': 'olive',
  },
  {
    'id': 'limejuice',
    'name': 'limejuice',
    'label': 'limejuice',
    'color': 'olive',
  },
  {
    'id': 'carrotjuice',
    'name': 'carrotjuice',
    'label': 'carrotjuice',
    'color': 'olive',
  },
  {
    'id': 'berryjuice',
    'name': 'berryjuice',
    'label': 'berryjuice',
    'color': 'olive',
  },
  {
    'id': 'applejuice',
    'name': 'applejuice',
    'label': 'applejuice',
    'color': 'olive',
  },
  {
    'id': 'poisonberryjuice',
    'name': 'poisonberryjuice',
    'label': 'poisonberryjuice',
    'color': 'olive',
  },
  {
    'id': 'watermelonjuice',
    'name': 'watermelonjuice',
    'label': 'watermelonjuice',
    'color': 'olive',
  },
  {
    'id': 'lemonjuice',
    'name': 'lemonjuice',
    'label': 'lemonjuice',
    'color': 'olive',
  },
  {
    'id': 'banana',
    'name': 'banana',
    'label': 'banana',
    'color': 'olive',
  },
  {
    'id': 'nothing',
    'name': 'nothing',
    'label': 'nothing',
    'color': 'olive',
  },
  {
    'id': 'laughter',
    'name': 'laughter',
    'label': 'laughter',
    'color': 'olive',
  },
  {
    'id': 'superlaughter',
    'name': 'superlaughter',
    'label': 'superlaughter',
    'color': 'olive',
  },
  {
    'id': 'potato_juice',
    'name': 'potato_juice',
    'label': 'potato_juice',
    'color': 'olive',
  },
  {
    'id': 'grapejuice',
    'name': 'grapejuice',
    'label': 'grapejuice',
    'color': 'olive',
  },
  {
    'id': 'milk',
    'name': 'milk',
    'label': 'milk',
    'color': 'olive',
  },
  {
    'id': 'soymilk',
    'name': 'soymilk',
    'label': 'soymilk',
    'color': 'olive',
  },
  {
    'id': 'cream',
    'name': 'cream',
    'label': 'cream',
    'color': 'olive',
  },
  {
    'id': 'coffee',
    'name': 'coffee',
    'label': 'coffee',
    'color': 'olive',
  },
  {
    'id': 'tea',
    'name': 'tea',
    'label': 'tea',
    'color': 'olive',
  },
  {
    'id': 'lemonade',
    'name': 'lemonade',
    'label': 'lemonade',
    'color': 'olive',
  },
  {
    'id': 'arnold_palmer',
    'name': 'arnold_palmer',
    'label': 'arnold_palmer',
    'color': 'olive',
  },
  {
    'id': 'icecoffee',
    'name': 'icecoffee',
    'label': 'icecoffee',
    'color': 'olive',
  },
  {
    'id': 'icetea',
    'name': 'icetea',
    'label': 'icetea',
    'color': 'olive',
  },
  {
    'id': 'space_cola',
    'name': 'space_cola',
    'label': 'space_cola',
    'color': 'olive',
  },
  {
    'id': 'nuka_cola',
    'name': 'nuka_cola',
    'label': 'nuka_cola',
    'color': 'olive',
  },
  {
    'id': 'grey_bull',
    'name': 'grey_bull',
    'label': 'grey_bull',
    'color': 'olive',
  },
  {
    'id': 'spacemountainwind',
    'name': 'spacemountainwind',
    'label': 'spacemountainwind',
    'color': 'olive',
  },
  {
    'id': 'dr_gibb',
    'name': 'dr_gibb',
    'label': 'dr_gibb',
    'color': 'olive',
  },
  {
    'id': 'space_up',
    'name': 'space_up',
    'label': 'space_up',
    'color': 'olive',
  },
  {
    'id': 'lemon_lime',
    'name': 'lemon_lime',
    'label': 'lemon_lime',
    'color': 'olive',
  },
  {
    'id': 'pwr_game',
    'name': 'pwr_game',
    'label': 'pwr_game',
    'color': 'olive',
  },
  {
    'id': 'shamblers',
    'name': 'shamblers',
    'label': 'shamblers',
    'color': 'olive',
  },
  {
    'id': 'sodawater',
    'name': 'sodawater',
    'label': 'sodawater',
    'color': 'olive',
  },
  {
    'id': 'tonic',
    'name': 'tonic',
    'label': 'tonic',
    'color': 'olive',
  },
  {
    'id': 'monkey_energy',
    'name': 'monkey_energy',
    'label': 'monkey_energy',
    'color': 'olive',
  },
  {
    'id': 'ice',
    'name': 'ice',
    'label': 'ice',
    'color': 'olive',
  },
  {
    'id': 'soy_latte',
    'name': 'soy_latte',
    'label': 'soy_latte',
    'color': 'olive',
  },
  {
    'id': 'cafe_latte',
    'name': 'cafe_latte',
    'label': 'cafe_latte',
    'color': 'olive',
  },
  {
    'id': 'doctor_delight',
    'name': 'doctor_delight',
    'label': 'doctor_delight',
    'color': 'olive',
  },
  {
    'id': 'chocolatepudding',
    'name': 'chocolatepudding',
    'label': 'chocolatepudding',
    'color': 'olive',
  },
  {
    'id': 'vanillapudding',
    'name': 'vanillapudding',
    'label': 'vanillapudding',
    'color': 'olive',
  },
  {
    'id': 'cherryshake',
    'name': 'cherryshake',
    'label': 'cherryshake',
    'color': 'olive',
  },
  {
    'id': 'bluecherryshake',
    'name': 'bluecherryshake',
    'label': 'bluecherryshake',
    'color': 'olive',
  },
  {
    'id': 'pumpkin_latte',
    'name': 'pumpkin_latte',
    'label': 'pumpkin_latte',
    'color': 'olive',
  },
  {
    'id': 'gibbfloats',
    'name': 'gibbfloats',
    'label': 'gibbfloats',
    'color': 'olive',
  },
  {
    'id': 'pumpkinjuice',
    'name': 'pumpkinjuice',
    'label': 'pumpkinjuice',
    'color': 'olive',
  },
  {
    'id': 'blumpkinjuice',
    'name': 'blumpkinjuice',
    'label': 'blumpkinjuice',
    'color': 'olive',
  },
  {
    'id': 'triple_citrus',
    'name': 'triple_citrus',
    'label': 'triple_citrus',
    'color': 'olive',
  },
  {
    'id': 'grape_soda',
    'name': 'grape_soda',
    'label': 'grape_soda',
    'color': 'olive',
  },
  {
    'id': 'chocolate_milk',
    'name': 'chocolate_milk',
    'label': 'chocolate_milk',
    'color': 'olive',
  },
  {
    'id': 'menthol',
    'name': 'menthol',
    'label': 'menthol',
    'color': 'olive',
  },
  {
    'id': 'grenadine',
    'name': 'grenadine',
    'label': 'grenadine',
    'color': 'olive',
  },
  {
    'id': 'parsnipjuice',
    'name': 'parsnipjuice',
    'label': 'parsnipjuice',
    'color': 'olive',
  },
  {
    'id': 'peachjuice',
    'name': 'peachjuice',
    'label': 'peachjuice',
    'color': 'olive',
  },
  {
    'id': 'cream_soda',
    'name': 'cream_soda',
    'label': 'cream_soda',
    'color': 'olive',
  },
  {
    'id': 'red_queen',
    'name': 'red_queen',
    'label': 'red_queen',
    'color': 'olive',
  },
  {
    'id': 'bungojuice',
    'name': 'bungojuice',
    'label': 'bungojuice',
    'color': 'olive',
  },
  {
    'id': 'drug',
    'name': 'drug',
    'label': 'drug',
    'color': 'olive',
  },
  {
    'id': 'space_drugs',
    'name': 'space_drugs',
    'label': 'space_drugs',
    'color': 'olive',
  },
  {
    'id': 'nicotine',
    'name': 'nicotine',
    'label': 'nicotine',
    'color': 'olive',
  },
  {
    'id': 'crank',
    'name': 'crank',
    'label': 'crank',
    'color': 'olive',
  },
  {
    'id': 'krokodil',
    'name': 'krokodil',
    'label': 'krokodil',
    'color': 'olive',
  },
  {
    'id': 'methamphetamine',
    'name': 'methamphetamine',
    'label': 'methamphetamine',
    'color': 'olive',
  },
  {
    'id': 'bath_salts',
    'name': 'bath_salts',
    'label': 'bath_salts',
    'color': 'olive',
  },
  {
    'id': 'aranesp',
    'name': 'aranesp',
    'label': 'aranesp',
    'color': 'olive',
  },
  {
    'id': 'happiness',
    'name': 'happiness',
    'label': 'happiness',
    'color': 'olive',
  },
  {
    'id': 'nutriment',
    'name': 'nutriment',
    'label': 'nutriment',
    'color': 'olive',
  },
  {
    'id': 'vitamin',
    'name': 'vitamin',
    'label': 'vitamin',
    'color': 'olive',
  },
  {
    'id': 'cooking_oil',
    'name': 'cooking_oil',
    'label': 'cooking_oil',
    'color': 'olive',
  },
  {
    'id': 'sugar',
    'name': 'sugar',
    'label': 'sugar',
    'color': 'olive',
  },
  {
    'id': 'virus_food',
    'name': 'virus_food',
    'label': 'virus_food',
    'color': 'olive',
  },
  {
    'id': 'soysauce',
    'name': 'soysauce',
    'label': 'soysauce',
    'color': 'olive',
  },
  {
    'id': 'ketchup',
    'name': 'ketchup',
    'label': 'ketchup',
    'color': 'olive',
  },
  {
    'id': 'capsaicin',
    'name': 'capsaicin',
    'label': 'capsaicin',
    'color': 'olive',
  },
  {
    'id': 'frostoil',
    'name': 'frostoil',
    'label': 'frostoil',
    'color': 'olive',
  },
  {
    'id': 'condensedcapsaicin',
    'name': 'condensedcapsaicin',
    'label': 'condensedcapsaicin',
    'color': 'olive',
  },
  {
    'id': 'sodiumchloride',
    'name': 'sodiumchloride',
    'label': 'sodiumchloride',
    'color': 'olive',
  },
  {
    'id': 'blackpepper',
    'name': 'blackpepper',
    'label': 'blackpepper',
    'color': 'olive',
  },
  {
    'id': 'coco',
    'name': 'coco',
    'label': 'coco',
    'color': 'olive',
  },
  {
    'id': 'hot_coco',
    'name': 'hot_coco',
    'label': 'hot_coco',
    'color': 'olive',
  },
  {
    'id': 'mushroomhallucinogen',
    'name': 'mushroomhallucinogen',
    'label': 'mushroomhallucinogen',
    'color': 'olive',
  },
  {
    'id': 'garlic',
    'name': 'garlic',
    'label': 'garlic',
    'color': 'olive',
  },
  {
    'id': 'sprinkles',
    'name': 'sprinkles',
    'label': 'sprinkles',
    'color': 'olive',
  },
  {
    'id': 'cornoil',
    'name': 'cornoil',
    'label': 'cornoil',
    'color': 'olive',
  },
  {
    'id': 'enzyme',
    'name': 'enzyme',
    'label': 'enzyme',
    'color': 'olive',
  },
  {
    'id': 'dry_ramen',
    'name': 'dry_ramen',
    'label': 'dry_ramen',
    'color': 'olive',
  },
  {
    'id': 'hot_ramen',
    'name': 'hot_ramen',
    'label': 'hot_ramen',
    'color': 'olive',
  },
  {
    'id': 'hell_ramen',
    'name': 'hell_ramen',
    'label': 'hell_ramen',
    'color': 'olive',
  },
  {
    'id': 'flour',
    'name': 'flour',
    'label': 'flour',
    'color': 'olive',
  },
  {
    'id': 'cherryjelly',
    'name': 'cherryjelly',
    'label': 'cherryjelly',
    'color': 'olive',
  },
  {
    'id': 'bluecherryjelly',
    'name': 'bluecherryjelly',
    'label': 'bluecherryjelly',
    'color': 'olive',
  },
  {
    'id': 'rice',
    'name': 'rice',
    'label': 'rice',
    'color': 'olive',
  },
  {
    'id': 'vanilla',
    'name': 'vanilla',
    'label': 'vanilla',
    'color': 'olive',
  },
  {
    'id': 'eggyolk',
    'name': 'eggyolk',
    'label': 'eggyolk',
    'color': 'olive',
  },
  {
    'id': 'corn_starch',
    'name': 'corn_starch',
    'label': 'corn_starch',
    'color': 'olive',
  },
  {
    'id': 'corn_syrup',
    'name': 'corn_syrup',
    'label': 'corn_syrup',
    'color': 'olive',
  },
  {
    'id': 'honey',
    'name': 'honey',
    'label': 'honey',
    'color': 'olive',
  },
  {
    'id': 'special',
    'name': 'special',
    'label': 'special',
    'color': 'olive',
  },
  {
    'id': 'mayonnaise',
    'name': 'mayonnaise',
    'label': 'mayonnaise',
    'color': 'olive',
  },
  {
    'id': 'tearjuice',
    'name': 'tearjuice',
    'label': 'tearjuice',
    'color': 'olive',
  },
  {
    'id': 'stabilized',
    'name': 'stabilized',
    'label': 'stabilized',
    'color': 'olive',
  },
  {
    'id': 'entpoly',
    'name': 'entpoly',
    'label': 'entpoly',
    'color': 'olive',
  },
  {
    'id': 'tinlux',
    'name': 'tinlux',
    'label': 'tinlux',
    'color': 'olive',
  },
  {
    'id': 'vitfro',
    'name': 'vitfro',
    'label': 'vitfro',
    'color': 'olive',
  },
  {
    'id': 'clownstears',
    'name': 'clownstears',
    'label': 'clownstears',
    'color': 'olive',
  },
  {
    'id': 'liquidelectricity',
    'name': 'liquidelectricity',
    'label': 'liquidelectricity',
    'color': 'olive',
  },
  {
    'id': 'astrotame',
    'name': 'astrotame',
    'label': 'astrotame',
    'color': 'olive',
  },
  {
    'id': 'caramel',
    'name': 'caramel',
    'label': 'caramel',
    'color': 'olive',
  },
  {
    'id': 'bbqsauce',
    'name': 'bbqsauce',
    'label': 'bbqsauce',
    'color': 'olive',
  },
  {
    'id': 'char',
    'name': 'char',
    'label': 'char',
    'color': 'olive',
  },
  {
    'id': 'medicine',
    'name': 'medicine',
    'label': 'medicine',
    'color': 'olive',
  },
  {
    'id': 'leporazine',
    'name': 'leporazine',
    'label': 'leporazine',
    'color': 'olive',
  },
  {
    'id': 'adminordrazine',
    'name': 'adminordrazine',
    'label': 'adminordrazine',
    'color': 'olive',
  },
  {
    'id': 'quantum_heal',
    'name': 'quantum_heal',
    'label': 'quantum_heal',
    'color': 'olive',
  },
  {
    'id': 'synaptizine',
    'name': 'synaptizine',
    'label': 'synaptizine',
    'color': 'olive',
  },
  {
    'id': 'synaphydramine',
    'name': 'synaphydramine',
    'label': 'synaphydramine',
    'color': 'olive',
  },
  {
    'id': 'inacusiate',
    'name': 'inacusiate',
    'label': 'inacusiate',
    'color': 'olive',
  },
  {
    'id': 'cryoxadone',
    'name': 'cryoxadone',
    'label': 'cryoxadone',
    'color': 'olive',
  },
  {
    'id': 'clonexadone',
    'name': 'clonexadone',
    'label': 'clonexadone',
    'color': 'olive',
  },
  {
    'id': 'pyroxadone',
    'name': 'pyroxadone',
    'label': 'pyroxadone',
    'color': 'olive',
  },
  {
    'id': 'rezadone',
    'name': 'rezadone',
    'label': 'rezadone',
    'color': 'olive',
  },
  {
    'id': 'spaceacillin',
    'name': 'spaceacillin',
    'label': 'spaceacillin',
    'color': 'olive',
  },
  {
    'id': 'silver_sulfadiazine',
    'name': 'silver_sulfadiazine',
    'label': 'silver_sulfadiazine',
    'color': 'olive',
  },
  {
    'id': 'oxandrolone',
    'name': 'oxandrolone',
    'label': 'oxandrolone',
    'color': 'olive',
  },
  {
    'id': 'styptic_powder',
    'name': 'styptic_powder',
    'label': 'styptic_powder',
    'color': 'olive',
  },
  {
    'id': 'salglu_solution',
    'name': 'salglu_solution',
    'label': 'salglu_solution',
    'color': 'olive',
  },
  {
    'id': 'mine_salve',
    'name': 'mine_salve',
    'label': 'mine_salve',
    'color': 'olive',
  },
  {
    'id': 'synthflesh',
    'name': 'synthflesh',
    'label': 'synthflesh',
    'color': 'olive',
  },
  {
    'id': 'charcoal',
    'name': 'charcoal',
    'label': 'charcoal',
    'color': 'olive',
  },
  {
    'id': 'system_cleaner',
    'name': 'system_cleaner',
    'label': 'system_cleaner',
    'color': 'olive',
  },
  {
    'id': 'liquid_solder',
    'name': 'liquid_solder',
    'label': 'liquid_solder',
    'color': 'olive',
  },
  {
    'id': 'omnizine',
    'name': 'omnizine',
    'label': 'omnizine',
    'color': 'olive',
  },
  {
    'id': 'calomel',
    'name': 'calomel',
    'label': 'calomel',
    'color': 'olive',
  },
  {
    'id': 'potass_iodide',
    'name': 'potass_iodide',
    'label': 'potass_iodide',
    'color': 'olive',
  },
  {
    'id': 'pen_acid',
    'name': 'pen_acid',
    'label': 'pen_acid',
    'color': 'olive',
  },
  {
    'id': 'sal_acid',
    'name': 'sal_acid',
    'label': 'sal_acid',
    'color': 'olive',
  },
  {
    'id': 'salbutamol',
    'name': 'salbutamol',
    'label': 'salbutamol',
    'color': 'olive',
  },
  {
    'id': 'perfluorodecalin',
    'name': 'perfluorodecalin',
    'label': 'perfluorodecalin',
    'color': 'olive',
  },
  {
    'id': 'ephedrine',
    'name': 'ephedrine',
    'label': 'ephedrine',
    'color': 'olive',
  },
  {
    'id': 'diphenhydramine',
    'name': 'diphenhydramine',
    'label': 'diphenhydramine',
    'color': 'olive',
  },
  {
    'id': 'morphine',
    'name': 'morphine',
    'label': 'morphine',
    'color': 'olive',
  },
  {
    'id': 'oculine',
    'name': 'oculine',
    'label': 'oculine',
    'color': 'olive',
  },
  {
    'id': 'atropine',
    'name': 'atropine',
    'label': 'atropine',
    'color': 'olive',
  },
  {
    'id': 'epinephrine',
    'name': 'epinephrine',
    'label': 'epinephrine',
    'color': 'olive',
  },
  {
    'id': 'strange_reagent',
    'name': 'strange_reagent',
    'label': 'strange_reagent',
    'color': 'olive',
  },
  {
    'id': 'mannitol',
    'name': 'mannitol',
    'label': 'mannitol',
    'color': 'olive',
  },
  {
    'id': 'neurine',
    'name': 'neurine',
    'label': 'neurine',
    'color': 'olive',
  },
  {
    'id': 'mutadone',
    'name': 'mutadone',
    'label': 'mutadone',
    'color': 'olive',
  },
  {
    'id': 'antihol',
    'name': 'antihol',
    'label': 'antihol',
    'color': 'olive',
  },
  {
    'id': 'stimulants',
    'name': 'stimulants',
    'label': 'stimulants',
    'color': 'olive',
  },
  {
    'id': 'pumpup',
    'name': 'pumpup',
    'label': 'pumpup',
    'color': 'olive',
  },
  {
    'id': 'insulin',
    'name': 'insulin',
    'label': 'insulin',
    'color': 'olive',
  },
  {
    'id': 'bicaridine',
    'name': 'bicaridine',
    'label': 'bicaridine',
    'color': 'olive',
  },
  {
    'id': 'kelotane',
    'name': 'kelotane',
    'label': 'kelotane',
    'color': 'olive',
  },
  {
    'id': 'antitoxin',
    'name': 'antitoxin',
    'label': 'antitoxin',
    'color': 'olive',
  },
  {
    'id': 'carthatoline',
    'name': 'carthatoline',
    'label': 'carthatoline',
    'color': 'olive',
  },
  {
    'id': 'hepanephrodaxon',
    'name': 'hepanephrodaxon',
    'label': 'hepanephrodaxon',
    'color': 'olive',
  },
  {
    'id': 'inaprovaline',
    'name': 'inaprovaline',
    'label': 'inaprovaline',
    'color': 'olive',
  },
  {
    'id': 'tricordrazine',
    'name': 'tricordrazine',
    'label': 'tricordrazine',
    'color': 'olive',
  },
  {
    'id': 'regen_jelly',
    'name': 'regen_jelly',
    'label': 'regen_jelly',
    'color': 'olive',
  },
  {
    'id': 'syndicate_nanites',
    'name': 'syndicate_nanites',
    'label': 'syndicate_nanites',
    'color': 'olive',
  },
  {
    'id': 'earthsblood',
    'name': 'earthsblood',
    'label': 'earthsblood',
    'color': 'olive',
  },
  {
    'id': 'haloperidol',
    'name': 'haloperidol',
    'label': 'haloperidol',
    'color': 'olive',
  },
  {
    'id': 'lavaland_extract',
    'name': 'lavaland_extract',
    'label': 'lavaland_extract',
    'color': 'olive',
  },
  {
    'id': 'changelingadrenaline',
    'name': 'changelingadrenaline',
    'label': 'changelingadrenaline',
    'color': 'olive',
  },
  {
    'id': 'changelinghaste',
    'name': 'changelinghaste',
    'label': 'changelinghaste',
    'color': 'olive',
  },
  {
    'id': 'corazone',
    'name': 'corazone',
    'label': 'corazone',
    'color': 'olive',
  },
  {
    'id': 'muscle_stimulant',
    'name': 'muscle_stimulant',
    'label': 'muscle_stimulant',
    'color': 'olive',
  },
  {
    'id': 'modafinil',
    'name': 'modafinil',
    'label': 'modafinil',
    'color': 'olive',
  },
  {
    'id': 'psicodine',
    'name': 'psicodine',
    'label': 'psicodine',
    'color': 'olive',
  },
  {
    'id': 'silibinin',
    'name': 'silibinin',
    'label': 'silibinin',
    'color': 'olive',
  },
  {
    'id': 'polypyr',
    'name': 'polypyr',
    'label': 'polypyr',
    'color': 'olive',
  },
  {
    'id': 'blood',
    'name': 'blood',
    'label': 'blood',
    'color': 'olive',
  },
  {
    'id': 'liquidgibs',
    'name': 'liquidgibs',
    'label': 'liquidgibs',
    'color': 'olive',
  },
  {
    'id': 'vaccine',
    'name': 'vaccine',
    'label': 'vaccine',
    'color': 'olive',
  },
  {
    'id': 'water',
    'name': 'water',
    'label': 'water',
    'color': 'olive',
  },
  {
    'id': 'holywater',
    'name': 'holywater',
    'label': 'holywater',
    'color': 'olive',
  },
  {
    'id': 'unholywater',
    'name': 'unholywater',
    'label': 'unholywater',
    'color': 'olive',
  },
  {
    'id': 'hellwater',
    'name': 'hellwater',
    'label': 'hellwater',
    'color': 'olive',
  },
  {
    'id': 'godblood',
    'name': 'godblood',
    'label': 'godblood',
    'color': 'olive',
  },
  {
    'id': 'lube',
    'name': 'lube',
    'label': 'lube',
    'color': 'olive',
  },
  {
    'id': 'spraytan',
    'name': 'spraytan',
    'label': 'spraytan',
    'color': 'olive',
  },
  {
    'id': 'mutationtoxin',
    'name': 'mutationtoxin',
    'label': 'mutationtoxin',
    'color': 'olive',
  },
  {
    'id': 'classic',
    'name': 'classic',
    'label': 'classic',
    'color': 'olive',
  },
  {
    'id': 'unstable',
    'name': 'unstable',
    'label': 'unstable',
    'color': 'olive',
  },
  {
    'id': 'felinid',
    'name': 'felinid',
    'label': 'felinid',
    'color': 'olive',
  },
  {
    'id': 'lizard',
    'name': 'lizard',
    'label': 'lizard',
    'color': 'olive',
  },
  {
    'id': 'fly',
    'name': 'fly',
    'label': 'fly',
    'color': 'olive',
  },
  {
    'id': 'moth',
    'name': 'moth',
    'label': 'moth',
    'color': 'olive',
  },
  {
    'id': 'pod',
    'name': 'pod',
    'label': 'pod',
    'color': 'olive',
  },
  {
    'id': 'jelly',
    'name': 'jelly',
    'label': 'jelly',
    'color': 'olive',
  },
  {
    'id': 'golem',
    'name': 'golem',
    'label': 'golem',
    'color': 'olive',
  },
  {
    'id': 'abductor',
    'name': 'abductor',
    'label': 'abductor',
    'color': 'olive',
  },
  {
    'id': 'android',
    'name': 'android',
    'label': 'android',
    'color': 'olive',
  },
  {
    'id': 'ipc',
    'name': 'ipc',
    'label': 'ipc',
    'color': 'olive',
  },
  {
    'id': 'squid',
    'name': 'squid',
    'label': 'squid',
    'color': 'olive',
  },
  {
    'id': 'skeleton',
    'name': 'skeleton',
    'label': 'skeleton',
    'color': 'olive',
  },
  {
    'id': 'zombie',
    'name': 'zombie',
    'label': 'zombie',
    'color': 'olive',
  },
  {
    'id': 'goofzombie',
    'name': 'goofzombie',
    'label': 'goofzombie',
    'color': 'olive',
  },
  {
    'id': 'ash',
    'name': 'ash',
    'label': 'ash',
    'color': 'olive',
  },
  {
    'id': 'supersoldier',
    'name': 'supersoldier',
    'label': 'supersoldier',
    'color': 'olive',
  },
  {
    'id': 'shadow',
    'name': 'shadow',
    'label': 'shadow',
    'color': 'olive',
  },
  {
    'id': 'slime_toxin',
    'name': 'slime_toxin',
    'label': 'slime_toxin',
    'color': 'olive',
  },
  {
    'id': 'mulligan',
    'name': 'mulligan',
    'label': 'mulligan',
    'color': 'olive',
  },
  {
    'id': 'aslimetoxin',
    'name': 'aslimetoxin',
    'label': 'aslimetoxin',
    'color': 'olive',
  },
  {
    'id': 'gluttonytoxin',
    'name': 'gluttonytoxin',
    'label': 'gluttonytoxin',
    'color': 'olive',
  },
  {
    'id': 'serotrotium',
    'name': 'serotrotium',
    'label': 'serotrotium',
    'color': 'olive',
  },
  {
    'id': 'copper',
    'name': 'copper',
    'label': 'copper',
    'color': 'olive',
  },
  {
    'id': 'hydrogen',
    'name': 'hydrogen',
    'label': 'hydrogen',
    'color': 'olive',
  },
  {
    'id': 'potassium',
    'name': 'potassium',
    'label': 'potassium',
    'color': 'olive',
  },
  {
    'id': 'mercury',
    'name': 'mercury',
    'label': 'mercury',
    'color': 'olive',
  },
  {
    'id': 'sulfur',
    'name': 'sulfur',
    'label': 'sulfur',
    'color': 'olive',
  },
  {
    'id': 'carbon',
    'name': 'carbon',
    'label': 'carbon',
    'color': 'olive',
  },
  {
    'id': 'chlorine',
    'name': 'chlorine',
    'label': 'chlorine',
    'color': 'olive',
  },
  {
    'id': 'fluorine',
    'name': 'fluorine',
    'label': 'fluorine',
    'color': 'olive',
  },
  {
    'id': 'sodium',
    'name': 'sodium',
    'label': 'sodium',
    'color': 'olive',
  },
  {
    'id': 'phosphorus',
    'name': 'phosphorus',
    'label': 'phosphorus',
    'color': 'olive',
  },
  {
    'id': 'lithium',
    'name': 'lithium',
    'label': 'lithium',
    'color': 'olive',
  },
  {
    'id': 'glycerol',
    'name': 'glycerol',
    'label': 'glycerol',
    'color': 'olive',
  },
  {
    'id': 'sterilizine',
    'name': 'sterilizine',
    'label': 'sterilizine',
    'color': 'olive',
  },
  {
    'id': 'iron',
    'name': 'iron',
    'label': 'iron',
    'color': 'olive',
  },
  {
    'id': 'gold',
    'name': 'gold',
    'label': 'gold',
    'color': 'olive',
  },
  {
    'id': 'silver',
    'name': 'silver',
    'label': 'silver',
    'color': 'olive',
  },
  {
    'id': 'uranium',
    'name': 'uranium',
    'label': 'uranium',
    'color': 'olive',
  },
  {
    'id': 'radium',
    'name': 'radium',
    'label': 'radium',
    'color': 'olive',
  },
  {
    'id': 'bluespace',
    'name': 'bluespace',
    'label': 'bluespace',
    'color': 'olive',
  },
  {
    'id': 'aluminium',
    'name': 'aluminium',
    'label': 'aluminium',
    'color': 'olive',
  },
  {
    'id': 'silicon',
    'name': 'silicon',
    'label': 'silicon',
    'color': 'olive',
  },
  {
    'id': 'fuel',
    'name': 'fuel',
    'label': 'fuel',
    'color': 'olive',
  },
  {
    'id': 'space_cleaner',
    'name': 'space_cleaner',
    'label': 'space_cleaner',
    'color': 'olive',
  },
  {
    'id': 'ez_clean',
    'name': 'ez_clean',
    'label': 'ez_clean',
    'color': 'olive',
  },
  {
    'id': 'cryptobiolin',
    'name': 'cryptobiolin',
    'label': 'cryptobiolin',
    'color': 'olive',
  },
  {
    'id': 'impedrezene',
    'name': 'impedrezene',
    'label': 'impedrezene',
    'color': 'olive',
  },
  {
    'id': 'nanomachines',
    'name': 'nanomachines',
    'label': 'nanomachines',
    'color': 'olive',
  },
  {
    'id': 'xenomicrobes',
    'name': 'xenomicrobes',
    'label': 'xenomicrobes',
    'color': 'olive',
  },
  {
    'id': 'fungalspores',
    'name': 'fungalspores',
    'label': 'fungalspores',
    'color': 'olive',
  },
  {
    'id': 'snail',
    'name': 'snail',
    'label': 'snail',
    'color': 'olive',
  },
  {
    'id': 'fluorosurfactant',
    'name': 'fluorosurfactant',
    'label': 'fluorosurfactant',
    'color': 'olive',
  },
  {
    'id': 'foaming_agent',
    'name': 'foaming_agent',
    'label': 'foaming_agent',
    'color': 'olive',
  },
  {
    'id': 'smart_foaming_agent',
    'name': 'smart_foaming_agent',
    'label': 'smart_foaming_agent',
    'color': 'olive',
  },
  {
    'id': 'ammonia',
    'name': 'ammonia',
    'label': 'ammonia',
    'color': 'olive',
  },
  {
    'id': 'diethylamine',
    'name': 'diethylamine',
    'label': 'diethylamine',
    'color': 'olive',
  },
  {
    'id': 'carbondioxide',
    'name': 'carbondioxide',
    'label': 'carbondioxide',
    'color': 'olive',
  },
  {
    'id': 'powder',
    'name': 'powder',
    'label': 'powder',
    'color': 'olive',
  },
  {
    'id': 'red',
    'name': 'red',
    'label': 'red',
    'color': 'olive',
  },
  {
    'id': 'orange',
    'name': 'orange',
    'label': 'orange',
    'color': 'olive',
  },
  {
    'id': 'yellow',
    'name': 'yellow',
    'label': 'yellow',
    'color': 'olive',
  },
  {
    'id': 'blue',
    'name': 'blue',
    'label': 'blue',
    'color': 'olive',
  },
  {
    'id': 'purple',
    'name': 'purple',
    'label': 'purple',
    'color': 'olive',
  },
  {
    'id': 'invisible',
    'name': 'invisible',
    'label': 'invisible',
    'color': 'olive',
  },
  {
    'id': 'black',
    'name': 'black',
    'label': 'black',
    'color': 'olive',
  },
  {
    'id': 'white',
    'name': 'white',
    'label': 'white',
    'color': 'olive',
  },
  {
    'id': 'plantnutriment',
    'name': 'plantnutriment',
    'label': 'plantnutriment',
    'color': 'olive',
  },
  {
    'id': 'eznutriment',
    'name': 'eznutriment',
    'label': 'eznutriment',
    'color': 'olive',
  },
  {
    'id': 'left4zednutriment',
    'name': 'left4zednutriment',
    'label': 'left4zednutriment',
    'color': 'olive',
  },
  {
    'id': 'robustharvestnutriment',
    'name': 'robustharvestnutriment',
    'label': 'robustharvestnutriment',
    'color': 'olive',
  },
  {
    'id': 'oil',
    'name': 'oil',
    'label': 'oil',
    'color': 'olive',
  },
  {
    'id': 'stable_plasma',
    'name': 'stable_plasma',
    'label': 'stable_plasma',
    'color': 'olive',
  },
  {
    'id': 'iodine',
    'name': 'iodine',
    'label': 'iodine',
    'color': 'olive',
  },
  {
    'id': 'carpet',
    'name': 'carpet',
    'label': 'carpet',
    'color': 'olive',
  },
  {
    'id': 'bromine',
    'name': 'bromine',
    'label': 'bromine',
    'color': 'olive',
  },
  {
    'id': 'phenol',
    'name': 'phenol',
    'label': 'phenol',
    'color': 'olive',
  },
  {
    'id': 'acetone',
    'name': 'acetone',
    'label': 'acetone',
    'color': 'olive',
  },
  {
    'id': 'colorful_reagent',
    'name': 'colorful_reagent',
    'label': 'colorful_reagent',
    'color': 'olive',
  },
  {
    'id': 'hair_dye',
    'name': 'hair_dye',
    'label': 'hair_dye',
    'color': 'olive',
  },
  {
    'id': 'barbers_aid',
    'name': 'barbers_aid',
    'label': 'barbers_aid',
    'color': 'olive',
  },
  {
    'id': 'concentrated_barbers_aid',
    'name': 'concentrated_barbers_aid',
    'label': 'concentrated_barbers_aid',
    'color': 'olive',
  },
  {
    'id': 'saltpetre',
    'name': 'saltpetre',
    'label': 'saltpetre',
    'color': 'olive',
  },
  {
    'id': 'lye',
    'name': 'lye',
    'label': 'lye',
    'color': 'olive',
  },
  {
    'id': 'drying_agent',
    'name': 'drying_agent',
    'label': 'drying_agent',
    'color': 'olive',
  },
  {
    'id': 'mutagenvirusfood',
    'name': 'mutagenvirusfood',
    'label': 'mutagenvirusfood',
    'color': 'olive',
  },
  {
    'id': 'synaptizinevirusfood',
    'name': 'synaptizinevirusfood',
    'label': 'synaptizinevirusfood',
    'color': 'olive',
  },
  {
    'id': 'plasmavirusfood',
    'name': 'plasmavirusfood',
    'label': 'plasmavirusfood',
    'color': 'olive',
  },
  {
    'id': 'weak',
    'name': 'weak',
    'label': 'weak',
    'color': 'olive',
  },
  {
    'id': 'uraniumvirusfood',
    'name': 'uraniumvirusfood',
    'label': 'uraniumvirusfood',
    'color': 'olive',
  },
  {
    'id': 'stable',
    'name': 'stable',
    'label': 'stable',
    'color': 'olive',
  },
  {
    'id': 'laughtervirusfood',
    'name': 'laughtervirusfood',
    'label': 'laughtervirusfood',
    'color': 'olive',
  },
  {
    'id': 'advvirusfood',
    'name': 'advvirusfood',
    'label': 'advvirusfood',
    'color': 'olive',
  },
  {
    'id': 'viralbase',
    'name': 'viralbase',
    'label': 'viralbase',
    'color': 'olive',
  },
  {
    'id': 'royal_bee_jelly',
    'name': 'royal_bee_jelly',
    'label': 'royal_bee_jelly',
    'color': 'olive',
  },
  {
    'id': 'romerol',
    'name': 'romerol',
    'label': 'romerol',
    'color': 'olive',
  },
  {
    'id': 'magillitis',
    'name': 'magillitis',
    'label': 'magillitis',
    'color': 'olive',
  },
  {
    'id': 'growthserum',
    'name': 'growthserum',
    'label': 'growthserum',
    'color': 'olive',
  },
  {
    'id': 'plastic_polymers',
    'name': 'plastic_polymers',
    'label': 'plastic_polymers',
    'color': 'olive',
  },
  {
    'id': 'glitter',
    'name': 'glitter',
    'label': 'glitter',
    'color': 'olive',
  },
  {
    'id': 'pink',
    'name': 'pink',
    'label': 'pink',
    'color': 'olive',
  },
  {
    'id': 'pax',
    'name': 'pax',
    'label': 'pax',
    'color': 'olive',
  },
  {
    'id': 'bz_metabolites',
    'name': 'bz_metabolites',
    'label': 'bz_metabolites',
    'color': 'olive',
  },
  {
    'id': 'concentrated_bz',
    'name': 'concentrated_bz',
    'label': 'concentrated_bz',
    'color': 'olive',
  },
  {
    'id': 'fake_cbz',
    'name': 'fake_cbz',
    'label': 'fake_cbz',
    'color': 'olive',
  },
  {
    'id': 'peaceborg',
    'name': 'peaceborg',
    'label': 'peaceborg',
    'color': 'olive',
  },
  {
    'id': 'confuse',
    'name': 'confuse',
    'label': 'confuse',
    'color': 'olive',
  },
  {
    'id': 'inabizine',
    'name': 'inabizine',
    'label': 'inabizine',
    'color': 'olive',
  },
  {
    'id': 'tire',
    'name': 'tire',
    'label': 'tire',
    'color': 'olive',
  },
  {
    'id': 'tranquility',
    'name': 'tranquility',
    'label': 'tranquility',
    'color': 'olive',
  },
  {
    'id': 'liquidadamantine',
    'name': 'liquidadamantine',
    'label': 'liquidadamantine',
    'color': 'olive',
  },
  {
    'id': 'spider_extract',
    'name': 'spider_extract',
    'label': 'spider_extract',
    'color': 'olive',
  },
  {
    'id': 'ratlight',
    'name': 'ratlight',
    'label': 'ratlight',
    'color': 'olive',
  },
  {
    'id': 'invisium',
    'name': 'invisium',
    'label': 'invisium',
    'color': 'olive',
  },
  {
    'id': 'thermite',
    'name': 'thermite',
    'label': 'thermite',
    'color': 'olive',
  },
  {
    'id': 'nitroglycerin',
    'name': 'nitroglycerin',
    'label': 'nitroglycerin',
    'color': 'olive',
  },
  {
    'id': 'stabilizing_agent',
    'name': 'stabilizing_agent',
    'label': 'stabilizing_agent',
    'color': 'olive',
  },
  {
    'id': 'clf3',
    'name': 'clf3',
    'label': 'clf3',
    'color': 'olive',
  },
  {
    'id': 'sorium',
    'name': 'sorium',
    'label': 'sorium',
    'color': 'olive',
  },
  {
    'id': 'liquid_dark_matter',
    'name': 'liquid_dark_matter',
    'label': 'liquid_dark_matter',
    'color': 'olive',
  },
  {
    'id': 'blackpowder',
    'name': 'blackpowder',
    'label': 'blackpowder',
    'color': 'olive',
  },
  {
    'id': 'flash_powder',
    'name': 'flash_powder',
    'label': 'flash_powder',
    'color': 'olive',
  },
  {
    'id': 'smoke_powder',
    'name': 'smoke_powder',
    'label': 'smoke_powder',
    'color': 'olive',
  },
  {
    'id': 'sonic_powder',
    'name': 'sonic_powder',
    'label': 'sonic_powder',
    'color': 'olive',
  },
  {
    'id': 'phlogiston',
    'name': 'phlogiston',
    'label': 'phlogiston',
    'color': 'olive',
  },
  {
    'id': 'napalm',
    'name': 'napalm',
    'label': 'napalm',
    'color': 'olive',
  },
  {
    'id': 'cryostylane',
    'name': 'cryostylane',
    'label': 'cryostylane',
    'color': 'olive',
  },
  {
    'id': 'pyrosium',
    'name': 'pyrosium',
    'label': 'pyrosium',
    'color': 'olive',
  },
  {
    'id': 'teslium',
    'name': 'teslium',
    'label': 'teslium',
    'color': 'olive',
  },
  {
    'id': 'energized_jelly',
    'name': 'energized_jelly',
    'label': 'energized_jelly',
    'color': 'olive',
  },
  {
    'id': 'firefighting_foam',
    'name': 'firefighting_foam',
    'label': 'firefighting_foam',
    'color': 'olive',
  },
  {
    'id': 'toxin',
    'name': 'toxin',
    'label': 'toxin',
    'color': 'olive',
  },
  {
    'id': 'amatoxin',
    'name': 'amatoxin',
    'label': 'amatoxin',
    'color': 'olive',
  },
  {
    'id': 'mutagen',
    'name': 'mutagen',
    'label': 'mutagen',
    'color': 'olive',
  },
  {
    'id': 'lexorin',
    'name': 'lexorin',
    'label': 'lexorin',
    'color': 'olive',
  },
  {
    'id': 'slimejelly',
    'name': 'slimejelly',
    'label': 'slimejelly',
    'color': 'olive',
  },
  {
    'id': 'minttoxin',
    'name': 'minttoxin',
    'label': 'minttoxin',
    'color': 'olive',
  },
  {
    'id': 'carpotoxin',
    'name': 'carpotoxin',
    'label': 'carpotoxin',
    'color': 'olive',
  },
  {
    'id': 'zombiepowder',
    'name': 'zombiepowder',
    'label': 'zombiepowder',
    'color': 'olive',
  },
  {
    'id': 'ghoulpowder',
    'name': 'ghoulpowder',
    'label': 'ghoulpowder',
    'color': 'olive',
  },
  {
    'id': 'mindbreaker',
    'name': 'mindbreaker',
    'label': 'mindbreaker',
    'color': 'olive',
  },
  {
    'id': 'plantbgone',
    'name': 'plantbgone',
    'label': 'plantbgone',
    'color': 'olive',
  },
  {
    'id': 'weedkiller',
    'name': 'weedkiller',
    'label': 'weedkiller',
    'color': 'olive',
  },
  {
    'id': 'pestkiller',
    'name': 'pestkiller',
    'label': 'pestkiller',
    'color': 'olive',
  },
  {
    'id': 'spore',
    'name': 'spore',
    'label': 'spore',
    'color': 'olive',
  },
  {
    'id': 'spore_burning',
    'name': 'spore_burning',
    'label': 'spore_burning',
    'color': 'olive',
  },
  {
    'id': 'chloralhydrate',
    'name': 'chloralhydrate',
    'label': 'chloralhydrate',
    'color': 'olive',
  },
  {
    'id': 'fakebeer',
    'name': 'fakebeer',
    'label': 'fakebeer',
    'color': 'olive',
  },
  {
    'id': 'coffeepowder',
    'name': 'coffeepowder',
    'label': 'coffeepowder',
    'color': 'olive',
  },
  {
    'id': 'teapowder',
    'name': 'teapowder',
    'label': 'teapowder',
    'color': 'olive',
  },
  {
    'id': 'mutetoxin',
    'name': 'mutetoxin',
    'label': 'mutetoxin',
    'color': 'olive',
  },
  {
    'id': 'staminatoxin',
    'name': 'staminatoxin',
    'label': 'staminatoxin',
    'color': 'olive',
  },
  {
    'id': 'polonium',
    'name': 'polonium',
    'label': 'polonium',
    'color': 'olive',
  },
  {
    'id': 'histamine',
    'name': 'histamine',
    'label': 'histamine',
    'color': 'olive',
  },
  {
    'id': 'formaldehyde',
    'name': 'formaldehyde',
    'label': 'formaldehyde',
    'color': 'olive',
  },
  {
    'id': 'venom',
    'name': 'venom',
    'label': 'venom',
    'color': 'olive',
  },
  {
    'id': 'fentanyl',
    'name': 'fentanyl',
    'label': 'fentanyl',
    'color': 'olive',
  },
  {
    'id': 'cyanide',
    'name': 'cyanide',
    'label': 'cyanide',
    'color': 'olive',
  },
  {
    'id': 'bad_food',
    'name': 'bad_food',
    'label': 'bad_food',
    'color': 'olive',
  },
  {
    'id': 'itching_powder',
    'name': 'itching_powder',
    'label': 'itching_powder',
    'color': 'olive',
  },
  {
    'id': 'initropidril',
    'name': 'initropidril',
    'label': 'initropidril',
    'color': 'olive',
  },
  {
    'id': 'pancuronium',
    'name': 'pancuronium',
    'label': 'pancuronium',
    'color': 'olive',
  },
  {
    'id': 'sodium_thiopental',
    'name': 'sodium_thiopental',
    'label': 'sodium_thiopental',
    'color': 'olive',
  },
  {
    'id': 'sulfonal',
    'name': 'sulfonal',
    'label': 'sulfonal',
    'color': 'olive',
  },
  {
    'id': 'amanitin',
    'name': 'amanitin',
    'label': 'amanitin',
    'color': 'olive',
  },
  {
    'id': 'lipolicide',
    'name': 'lipolicide',
    'label': 'lipolicide',
    'color': 'olive',
  },
  {
    'id': 'coniine',
    'name': 'coniine',
    'label': 'coniine',
    'color': 'olive',
  },
  {
    'id': 'spewium',
    'name': 'spewium',
    'label': 'spewium',
    'color': 'olive',
  },
  {
    'id': 'curare',
    'name': 'curare',
    'label': 'curare',
    'color': 'olive',
  },
  {
    'id': 'heparin',
    'name': 'heparin',
    'label': 'heparin',
    'color': 'olive',
  },
  {
    'id': 'rotatium',
    'name': 'rotatium',
    'label': 'rotatium',
    'color': 'olive',
  },
  {
    'id': 'skewium',
    'name': 'skewium',
    'label': 'skewium',
    'color': 'olive',
  },
  {
    'id': 'anacea',
    'name': 'anacea',
    'label': 'anacea',
    'color': 'olive',
  },
  {
    'id': 'acid',
    'name': 'acid',
    'label': 'acid',
    'color': 'olive',
  },
  {
    'id': 'fluacid',
    'name': 'fluacid',
    'label': 'fluacid',
    'color': 'olive',
  },
  {
    'id': 'delayed',
    'name': 'delayed',
    'label': 'delayed',
    'color': 'olive',
  },
  {
    'id': 'mimesbane',
    'name': 'mimesbane',
    'label': 'mimesbane',
    'color': 'olive',
  },
  {
    'id': 'bonehurtingjuice',
    'name': 'bonehurtingjuice',
    'label': 'bonehurtingjuice',
    'color': 'olive',
  },
  {
    'id': 'bungotoxin',
    'name': 'bungotoxin',
    'label': 'bungotoxin',
    'color': 'olive',
  },
  // END
  {
    'id': 'hydrogen',
    'name': 'Hydrogen',
    'label': 'H₂',
    'color': 'white',
  },
];

export const getGasLabel = (gasId, fallbackValue) => {
  const gasSearchString = String(gasId).toLowerCase();
  const gas = GASES.find(gas => gas.id === gasSearchString
    || gas.name.toLowerCase() === gasSearchString);
  return gas && gas.label
    || fallbackValue
    || gasId;
};

export const getGasColor = gasId => {
  const gasSearchString = String(gasId).toLowerCase();
  const gas = GASES.find(gas => gas.id === gasSearchString
    || gas.name.toLowerCase() === gasSearchString);
  return gas && gas.color;
};
