/datum/unit_test/click_cd_tests/Run()
	var/mob/living/carbon/human/spawned_human = new(run_loc_floor_bottom_left)
	spawned_human.clear_all_action_cooldowns()
	spawned_human.add_action_cooldown(CD_GROUP_USER_ACTION, 100)
	TEST_ASSERT_EQUAL(100, spawned_human.next_action_max, "Expected the next users action to be equal to 100. The unit test or add_action_cooldown seems to be wrong.")
	spawned_human.add_action_cooldown(CD_GROUP_GUARDIAN, 200)
	TEST_ASSERT_EQUAL(200, spawned_human.next_action_max, "Expected the next users action to be equal to 200. add_action_cooldown seems to be wrong. (Presumably the max part of it)")
	spawned_human.add_action_cooldown(CD_GROUP_EXTERNAL, 150)
	TEST_ASSERT_EQUAL(200, spawned_human.next_action_max, "Expected the next users action to be equal to 200. add_action_cooldown seems to be wrong. (Presumably the max part of it)")
	spawned_human.override_action_cooldown(CD_GROUP_GUARDIAN, 120)
	TEST_ASSERT_EQUAL(150, spawned_human.next_action_max, "Expected the next users action to be equal to 150. override_action_cooldown seems to be wrong.")
	spawned_human.clear_action_cooldown(CD_GROUP_EXTERNAL)
	TEST_ASSERT_EQUAL(120, spawned_human.next_action_max, "Expected the next users action to be equal to 150. clear_action_cooldown seems to be wrong.")
	spawned_human.clear_all_action_cooldowns()
	TEST_ASSERT_EQUAL(0, spawned_human.next_action_max, "Expected the next users action to be equal to 0. clear_all_action_cooldowns seems to be wrong.")
	// Test modified action speeds
	spawned_human.set_action_modifier(CD_GROUP_USER_ACTION, 0.5)
	spawned_human.add_action_cooldown(CD_GROUP_USER_ACTION, 100)
	TEST_ASSERT_EQUAL(100, spawned_human.next_action_max, "Expected the next users action to be equal to 50. The set_action_modifier seems to be wrong.")
	// Everything seems fine
	qdel(spawned_human)
