name: Test

on: 
  pull_request:
    types: [closed]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: octokit/graphql-action@v2.x
      id: get_latest_release
      with:
        owner: ${{ github.event.repository.owner.login }}
        repo: ${{ github.event.repository.name }}
        pr: ${{ github.event.pull_request.number }}
        query: |
          query pullrequest {
            repository(name: $repo, owner: $owner) {
              pullRequest(number: $pr) {
                body
              }
            }
          }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - run: "echo 'latest release: ${{ steps.get_latest_release.outputs.data }}'"
