name: Test

on: 
  pull_request:
    types: [closed]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: octokit/graphql-action@v2.x
      id: get_latest_release
      with:
        query: |
          query pullrequest {
            repository(name: "$repo", owner: "$owner") {
              pullRequest(number: 3) {
                body
              }
            }
          }
        owner: ${{ github.event.repository.owner.name }}
        repo: ${{ github.event.repository.name }}
        pr: ${{ github.event.pull_request.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: "echo 'latest release: ${{ steps.get_latest_release.outputs.data }}'"
