name: Mark pull requests as stale

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: "This PR has been marked as stale due to being in an unmergable state for 7 days. Please resolve any conflicts and add testing evidence, then contact a project maintainer to have the stale label removed."
        stale-pr-label: 'Stale'
        any-of-pr-labels: 'Needs Testing Evidence,Merge Conflict'
        days-before-stale: -1
        days-before-close: -1
        days-before-pr-stale: 7
        days-before-pr-close: 5
        remove-pr-stale-when-updated: true
        labels-to-remove-when-unstale: 'Stale'
